"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var BaseMap_1 = require("./BaseMap");
var BaseDevice_1 = require("../../../devices/PLC/BaseDevice");
var CountField_1 = require("../../../meta/CountField");
var meta_1 = require("../../../meta/PLC/meta");
var SdcSoftDevice_1 = require("../../../devices/SdcSoftDevice");
var FixedValueField_1 = require("../../../meta/FixedValueField");
var gfrm_1 = require("@sdcsoft/gfrm");
module.exports = /** @class */ (function (_super) {
    __extends(Map_PLC_RanMeiDaoReYou, _super);
    function Map_PLC_RanMeiDaoReYou() {
        var _this = _super.call(this) || this;
        _this.addPoint(new CountField_1.CountField(BaseDevice_1.PLC.KEY_POINT_ZHU_YOU_BENG, "注油泵"));
        _this.addPoint(new CountField_1.CountField(BaseDevice_1.PLC.KEY_POINT_XUN_HUAN_BENG, "循环泵"));
        _this.addPoint(new CountField_1.CountField(BaseDevice_1.PLC.KEY_POINT_GU_FENG_FAN, "鼓风"));
        _this.addPoint(new CountField_1.CountField(BaseDevice_1.PLC.KEY_POINT_YIN_FENG_FAN, "引风"));
        _this.addPoint(new CountField_1.CountField(BaseDevice_1.PLC.KEY_POINT_LU_PAI_FAN, "炉排"));
        _this.addPoint(new CountField_1.CountField(BaseDevice_1.PLC.KEY_POINT_CHU_ZHA_FAN, "出渣"));
        _this.addPoint(new meta_1.BaseInfoField(SdcSoftDevice_1.SdcSoftDevice.KEY_POINT_RUN_HOURS, 9, 2, "运行小时数", "时"));
        _this.addPoint(new meta_1.BaseInfoField(SdcSoftDevice_1.SdcSoftDevice.KEY_POINT_RUN_DAYS, 11, 2, "运行天数", "天"));
        _this.addPoint(new meta_1.BaseInfoField(SdcSoftDevice_1.SdcSoftDevice.KEY_POINT_SYSTEM_STATUS, 13, 2, "系统状态", '', BaseMap_1.Map_PLC.coms_status));
        _this.addPoint(new FixedValueField_1.FixedValueField(SdcSoftDevice_1.SdcSoftDevice.KEY_POINT_POWER, "燃料", 2, Map_PLC_RanMeiDaoReYou.coms_power));
        _this.addPoint(new FixedValueField_1.FixedValueField(SdcSoftDevice_1.SdcSoftDevice.KEY_POINT_MEDIA, "介质", 2, Map_PLC_RanMeiDaoReYou.coms_media));
        _this.addPoint(new meta_1.BaseInfoField("ba_shuiweizhuangtai", 19, 2, "液位状态", '', Map_PLC_RanMeiDaoReYou.coms_level));
        _this.addPoint(new meta_1.MockField(gfrm_1.GroupFieldsRelationalMapping.KEY_MOCK_HuiLiuWenDu, 35, 4, "进口温度", "℃"));
        _this.addPoint(new meta_1.MockField(gfrm_1.GroupFieldsRelationalMapping.KEY_MOCK_ChuKouWenDu, 39, 4, "出口温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_gaoweicaowendu", 43, 4, "高位槽温度", "℃"));
        _this.addPoint(new meta_1.MockField(gfrm_1.GroupFieldsRelationalMapping.KEY_MOCK_PaiYanWenDu, 47, 4, "排烟温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_refengwendu", 51, 4, "热风温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_lutangwendu1", 55, 4, "炉膛温度1", "℃"));
        _this.addPoint(new meta_1.MockField("mo_lutangwendu2", 59, 4, "炉膛温度2", "℃"));
        _this.addPoint(new meta_1.MockField("mo_lutangwendu3", 63, 4, "炉膛温度3", "℃"));
        _this.addPoint(new meta_1.MockField("mo_lutangwendu", 67, 4, "炉膛温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_lutangchukouwendu", 71, 4, "炉膛出口温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_shengmeiqijinkouwendu", 75, 4, "省煤器进口温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_shengmeiqichukouwendu", 79, 4, "省煤器出口温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_yangqihanliang", 83, 4, "氧气含量", "%"));
        _this.addPoint(new meta_1.MockField("mo_yinfengjipinlufankui", 87, 4, "引风机频率反馈", "Hz"));
        _this.addPoint(new meta_1.MockField("mo_gufengjipinlufankui", 91, 4, "鼓风机频率反馈", "Hz"));
        _this.addPoint(new meta_1.MockField("mo_lupaipinlufankui", 95, 4, "炉排频率反馈", "Hz"));
        _this.addPoint(new meta_1.MockField("mo_jinkouyali", 99, 4, "进口压力", "MPa"));
        _this.addPoint(new meta_1.MockField("mo_chukouyali", 103, 4, "出口压力", "MPa"));
        _this.addPoint(new meta_1.MockField("mo_danqiyali", 107, 4, "氮气压力", "KPa"));
        _this.addPoint(new meta_1.MockField("mo_lutangyali", 111, 4, "炉膛压力", "KPa"));
        _this.addPoint(new meta_1.MockField("mo_gaoweicaoyewei", 115, 4, "高位槽液位", "%"));
        _this.addPoint(new meta_1.MockField("mo_daoreyouliuliang", 119, 4, "导热油流量", "%"));
        _this.addPoint(new meta_1.MockField("mo_diandongdiaojiefakaidufankui", 123, 4, "电动调节阀开度反馈", "%"));
        _this.addPoint(new meta_1.MockField("mo_jinyouhuiyouyacha", 127, 4, "进油回油压差", "MPa"));
        _this.addPoint(new meta_1.MockField("mo_chuyouguanwendu", 131, 4, "储油罐温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_chuyouguanyewei", 135, 4, "储油罐液位", "%"));
        _this.addPoint(new meta_1.MockField("mo_1#zhiguanwendu", 139, 4, "1#支管温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_2#zhiguanwendu", 143, 4, "2#支管温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_3#zhiguanwendu", 147, 4, "3#支管温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_4#zhiguanwendu", 151, 4, "4#支管温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_5#zhiguanwendu", 155, 4, "5#支管温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_6#zhiguanwendu", 159, 4, "6#支管温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_7#zhiguanwendu", 163, 4, "7#支管温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_8#zhiguanwendu", 167, 4, "8#支管温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_9#zhiguanwendu", 171, 4, "9#支管温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_10#zhiguanwendu", 175, 4, "10#支管温度", "℃"));
        _this.addPoint(new meta_1.SettingField("se_chukouwenduqiluwendusheding", 248, 4, "出口温度起炉温度设定", "℃"));
        _this.addPoint(new meta_1.SettingField("se_chukouwendubidiaowendusheding", 252, 4, "出口温度比调温度设定", "℃"));
        _this.addPoint(new meta_1.SettingField("se_chukouwendutingluwendusheding", 256, 4, "出口温度停炉温度设定", "℃"));
        _this.addPoint(new meta_1.SettingField("se_chukouwenduchaogaobaojingwendusheding", 260, 4, "出口温度超高报警温度设定", "℃"));
        _this.addPoint(new meta_1.SettingField("se_paiyanwenduchaogaobaojingsheding", 264, 4, "排烟温度超高报警设定", "℃"));
        _this.addPoint(new meta_1.SettingField("se_gaoweicaoyouweidisheding", 268, 4, "高位槽油位低设定", "%"));
        _this.addPoint(new meta_1.SettingField("se_gaoweicaoyouweigaosheding", 272, 4, "高位槽油位高设定", "%"));
        _this.addPoint(new meta_1.SettingField("se_anquanyouwensheding", 276, 4, "安全油温设定", "℃"));
        _this.addPoint(new meta_1.SettingField("se_yinfengjipinlusheding", 280, 4, "引风机频率设定", "Hz"));
        _this.addPoint(new meta_1.SettingField("se_gufengjipinlusheding", 284, 4, "鼓风机频率设定", "Hz"));
        _this.addPoint(new meta_1.SettingField("se_lupaipinlusheding", 288, 4, "炉排频率设定", "Hz"));
        _this.addPoint(new meta_1.SettingField("se_jinchukouyachagaobaojingsheding", 292, 4, "进出口压差高报警设定", "MPa"));
        _this.addPoint(new meta_1.SettingField("se_jinchukouyachadibaojingsheding", 296, 4, "进出口压差低报警设定", "Mpa"));
        _this.addPoint(new meta_1.SettingField("se_liuliangxiaxianbaojing", 300, 4, "流量下限报警", "m³/h"));
        _this.addPoint(new meta_1.SettingField("se_liuliangjidibaojing", 304, 4, "流量极低报警", "m³/h"));
        _this.addPoint(new meta_1.SettingField("se_danqiyalidisheding", 308, 4, "氮气压力低设定", "KPa"));
        _this.addPoint(new meta_1.SettingField("se_danqiyaligaosheding", 312, 4, "氮气压力高设定", "KPa"));
        _this.addPoint(new meta_1.SettingField("se_diandongfashoudongkaidusheding", 316, 4, "电动阀手动开度设定", "%"));
        _this.addPoint(new meta_1.SettingField("se_mubiaoyachasheding", 320, 4, "目标压差设定", "Mpa"));
        _this.addPoint(new meta_1.SettingField("se_zhiguanchaowenbaojingsheding", 324, 4, "支管超温报警设定", "℃"));
        _this.addPoint(new meta_1.DeviceField("de_yinfengshoudong/zidong", 368, 2, "引风", Map_PLC_RanMeiDaoReYou.coms_atuo));
        _this.addPoint(new meta_1.DeviceField(BaseDevice_1.PLC.KEY_POINT_YIN_FENG_FAN_1, 370, 2, "引风", Map_PLC_RanMeiDaoReYou.coms_start_stop));
        _this.addPoint(new meta_1.DeviceField("de_gufengshoudong/zidong", 372, 2, "鼓风", Map_PLC_RanMeiDaoReYou.coms_atuo));
        _this.addPoint(new meta_1.DeviceField(BaseDevice_1.PLC.KEY_POINT_GU_FENG_FAN_1, 374, 2, "鼓风", Map_PLC_RanMeiDaoReYou.coms_start_stop));
        _this.addPoint(new meta_1.DeviceField("de_lupaishoudong/zidong", 376, 2, "炉排", Map_PLC_RanMeiDaoReYou.coms_atuo));
        _this.addPoint(new meta_1.DeviceField(BaseDevice_1.PLC.KEY_POINT_LU_PAI_FAN_1, 378, 2, "炉排", Map_PLC_RanMeiDaoReYou.coms_start_stop));
        _this.addPoint(new meta_1.DeviceField("de_chuzhashoudong/zidong", 380, 2, "除渣", Map_PLC_RanMeiDaoReYou.coms_atuo));
        _this.addPoint(new meta_1.DeviceField(BaseDevice_1.PLC.KEY_POINT_CHU_ZHA_FAN_1, 382, 2, "除渣", Map_PLC_RanMeiDaoReYou.coms_start_stop));
        _this.addPoint(new meta_1.DeviceField("de_1#xunhuanbengshoudong/zidong", 384, 2, "1#循环泵", Map_PLC_RanMeiDaoReYou.coms_atuo));
        _this.addPoint(new meta_1.DeviceField(BaseDevice_1.PLC.KEY_POINT_XUN_HUAN_BENG_1, 386, 2, "1#循环泵", Map_PLC_RanMeiDaoReYou.coms_start_stop));
        _this.addPoint(new meta_1.DeviceField("de_2#xunhuanbengshoudong/zidong", 388, 2, "2#循环泵", Map_PLC_RanMeiDaoReYou.coms_atuo));
        _this.addPoint(new meta_1.DeviceField(BaseDevice_1.PLC.KEY_POINT_XUN_HUAN_BENG_2, 390, 2, "2#循环泵", Map_PLC_RanMeiDaoReYou.coms_start_stop));
        _this.addPoint(new meta_1.DeviceField("de_3#xunhuanbengshoudong/zidong", 392, 2, "3#循环泵", Map_PLC_RanMeiDaoReYou.coms_atuo));
        _this.addPoint(new meta_1.DeviceField(BaseDevice_1.PLC.KEY_POINT_XUN_HUAN_BENG_3, 394, 2, "3#循环泵", Map_PLC_RanMeiDaoReYou.coms_start_stop));
        _this.addPoint(new meta_1.DeviceField("de_zhuyoubengshoudong/zidong", 396, 2, "注油泵", Map_PLC_RanMeiDaoReYou.coms_atuo));
        _this.addPoint(new meta_1.DeviceField(BaseDevice_1.PLC.KEY_POINT_ZHU_YOU_BENG_1, 398, 2, "注油泵", Map_PLC_RanMeiDaoReYou.coms_start_stop));
        _this.addPoint(new meta_1.ExceptionField("ex_yinfengjibianpinqiguzhang", 448, 2, "引风机变频器故障", 0, meta_1.ExceptionField.Exception_Error));
        _this.addPoint(new meta_1.ExceptionField("ex_gufengjibianpinqiguzhang", 448, 2, "鼓风机变频器故障", 1, meta_1.ExceptionField.Exception_Error));
        _this.addPoint(new meta_1.ExceptionField("ex_lupaibianpinqiguzhang", 448, 2, "炉排变频器故障", 2, meta_1.ExceptionField.Exception_Error));
        _this.addPoint(new meta_1.ExceptionField("ex_chuzhajiguzhang", 448, 2, "除渣机故障", 3, meta_1.ExceptionField.Exception_Error));
        _this.addPoint(new meta_1.ExceptionField("ex_shangmeijiguzhang", 448, 2, "上煤机故障", 4, meta_1.ExceptionField.Exception_Error));
        _this.addPoint(new meta_1.ExceptionField("ex_1#xunhuanbengguzhang", 448, 2, "1#循环泵故障", 5));
        _this.addPoint(new meta_1.ExceptionField("ex_2#xunhuanbengguzhang", 448, 2, "2#循环泵故障", 6));
        _this.addPoint(new meta_1.ExceptionField("ex_3#xunhuanbengguzhang", 448, 2, "3#循环泵故障", 7));
        _this.addPoint(new meta_1.ExceptionField("ex_zhuyoubengguzhang", 448, 2, "注油泵故障", 8, meta_1.ExceptionField.Exception_Error));
        _this.addPoint(new meta_1.ExceptionField("ex_jinchukouyachachaogao", 448, 2, "进出口压差超高", 9, meta_1.ExceptionField.Exception_Error));
        _this.addPoint(new meta_1.ExceptionField("ex_jinchukouyachachaodi", 448, 2, "进出口压差超低", 10));
        _this.addPoint(new meta_1.ExceptionField(gfrm_1.GroupFieldsRelationalMapping.KEY_Expt_PaiYanWenDuChaoGao, 448, 2, "排烟温度超高", 11, meta_1.ExceptionField.Exception_Error));
        _this.addPoint(new meta_1.ExceptionField(gfrm_1.GroupFieldsRelationalMapping.KEY_Expt_ChuKouWenDuChaoGao, 448, 2, "出口温度超高", 12, meta_1.ExceptionField.Exception_Error));
        _this.addPoint(new meta_1.ExceptionField("ex_liuliangxiaxianbaojing", 448, 2, "流量下限报警", 13));
        _this.addPoint(new meta_1.ExceptionField("ex_liuliangjidibaojing", 448, 2, "流量极低报警", 14));
        _this.addPoint(new meta_1.ExceptionField(gfrm_1.GroupFieldsRelationalMapping.KEY_Expt_JiXianDiShuiWei, 448, 2, "缺油报警（浮球）", 15, meta_1.ExceptionField.Exception_Error), "ex_queyoubaojing_fuqiu_");
        _this.addPoint(new meta_1.ExceptionField("ex_chuyouwenduchuanganqiguzhang", 450, 2, "出油温度传感器故障", 0));
        _this.addPoint(new meta_1.ExceptionField("ex_huiyouwenduchuanganqiguzhang", 450, 2, "回油温度传感器故障", 1));
        _this.addPoint(new meta_1.ExceptionField("ex_paiyanwenduchuanganqiguzhang", 450, 2, "排烟温度传感器故障", 2));
        _this.addPoint(new meta_1.ExceptionField("ex_xunhuanbengliansuoguzhang", 450, 2, "循环泵连锁故障", 3));
        _this.addPoint(new meta_1.ExceptionField("ex_wendushedingcuowuguzhang", 450, 2, "温度设定错误故障", 4));
        _this.addPoint(new meta_1.ExceptionField(gfrm_1.GroupFieldsRelationalMapping.KEY_Expt_JiXianDiShuiWei, 450, 2, "高位油槽油位低报警", 5), "ex_gaoweiyoucaoyouweidibaojing");
        _this.addPoint(new meta_1.ExceptionField(gfrm_1.GroupFieldsRelationalMapping.KEY_Expt_JiXianGaoShuiWei, 450, 2, "高位油槽油位高报警", 6), "ex_gaoweiyoucaoyouweigaobaojing");
        _this.addPoint(new meta_1.ExceptionField("ex_1#zhiguanchaowenbaojing", 450, 2, "1#支管超温报警", 7));
        _this.addPoint(new meta_1.ExceptionField("ex_2#zhiguanchaowenbaojing", 450, 2, "2#支管超温报警", 8));
        _this.addPoint(new meta_1.ExceptionField("ex_3#zhiguanchaowenbaojing", 450, 2, "3#支管超温报警", 9));
        _this.addPoint(new meta_1.ExceptionField("ex_4#zhiguanchaowenbaojing", 450, 2, "4#支管超温报警", 10));
        _this.addPoint(new meta_1.ExceptionField("ex_5#zhiguanchaowenbaojing", 450, 2, "5#支管超温报警", 11));
        _this.addPoint(new meta_1.ExceptionField("ex_6#zhiguanchaowenbaojing", 450, 2, "6#支管超温报警", 12));
        _this.addPoint(new meta_1.ExceptionField("ex_7#zhiguanchaowenbaojing", 450, 2, "7#支管超温报警", 13));
        _this.addPoint(new meta_1.ExceptionField("ex_8#zhiguanchaowenbaojing", 450, 2, "8#支管超温报警", 14));
        _this.addPoint(new meta_1.ExceptionField("ex_9#zhiguanchaowenbaojing", 450, 2, "9#支管超温报警", 15));
        _this.addPoint(new meta_1.ExceptionField("ex_10#zhiguanchaowenbaojing", 452, 2, "10#支管超温报警", 0));
        _this.addPoint(new meta_1.ExceptionField("ex_PLCguzhangbaojing", 452, 2, "PLC故障报警", 1, meta_1.ExceptionField.Exception_Error));
        _this.addPoint(new meta_1.ExceptionField(gfrm_1.GroupFieldsRelationalMapping.KEY_Expt_ChaoYa, 452, 2, "压力高报警（电接点压力表）", 2, meta_1.ExceptionField.Exception_Error));
        _this.addPoint(new meta_1.ExceptionField(gfrm_1.GroupFieldsRelationalMapping.KEY_Expt_DiYa, 452, 2, "压力低报警（电接点压力表）", 3));
        return _this;
    }
    return Map_PLC_RanMeiDaoReYou;
}(BaseMap_1.Map_PLC));
