"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var CTL_NJZJ_IP_485_1749_1 = require("../NJZJ/CTL_NJZJ_IP_485_1749");
var meta_1 = require("../../../../meta/NJZJ/485/meta");
var meta_2 = require("../../../../meta/NJZJ/meta");
module.exports = /** @class */ (function (_super) {
    __extends(Map_CTL_BJKN_IP, _super);
    function Map_CTL_BJKN_IP() {
        var _this = _super.call(this) || this;
        _this.pointMap.remove('ex_1#guodianliubaojing');
        _this.pointMap.remove('ex_2#guodianliubaojing');
        _this.pointMap.remove('ex_3#guodianliubaojing');
        _this.pointMap.remove('ex_4#guodianliubaojing');
        _this.pointMap.remove('ex_5#guodianliubaojing');
        _this.pointMap.remove('ex_gufengjiguzhangbaojing');
        _this.pointMap.remove('ex_jiezhigaowenbaojing');
        _this.pointMap.remove('ex_jiezhidiwenbaojing');
        _this.pointMap.remove('ex_shineiwenduchuanganqiguzhang');
        _this.pointMap.remove('ex_1#dianliufankuichuanganqiguzhang');
        _this.pointMap.remove('ex_2#dianliufankuichuanganqiguzhang');
        _this.pointMap.remove('ex_3#dianliufankuichuanganqiguzhang');
        _this.pointMap.remove('ex_4#dianliufankuichuanganqiguzhang');
        _this.pointMap.remove('ex_5#dianliufankuichuanganqiguzhang');
        _this.pointMap.remove('ex_jiezhiwenduchuanganqiguzhang');
        _this.pointMap.remove('ex_xiyuwenduchuanganqiguzhang');
        _this.pointMap.remove('ex_huanjingwenduchuanganqiguzhang');
        _this.pointMap.remove('ex_jiezhiyalichuanganqiguzhang');
        _this.pointMap.remove('mo_1#dianliufankui');
        _this.pointMap.remove('mo_2#dianliufankui');
        _this.pointMap.remove('mo_3#dianliufankui');
        _this.pointMap.remove('mo_4#dianliufankui');
        _this.pointMap.remove('mo_5#dianliufankui');
        _this.pointMap.remove('mo_jiezhiwendu');
        _this.pointMap.remove('mo_xiyuwendu');
        _this.pointMap.remove('mo_huanjingwendu');
        _this.pointMap.remove('mo_jiezhiyali');
        // this.addPoint(new BaseInfoField("se_fangdongqiyong", 1752, 2, "防冻启用", '', Map_CTL_BJKN_IP.coms_open_close));
        _this.addPoint(new meta_2.SettingField("se_fangdongtingluwendu", 1754, 2, "防冻停炉温度", "℃"));
        _this.addPoint(new meta_2.SettingField("se_fangdongqiluwendu", 1756, 2, "防冻启炉温度", "℃"));
        _this.addPoint(new meta_1.WeekField("se_teshumoshishifouqiyong", 1758, 2, "特殊模式是否启用", '', Map_CTL_BJKN_IP.coms_valid));
        _this.addPoint(new meta_1.WeekField("se_zhourimoshi", 1760, 2, "周日模式", '', Map_CTL_BJKN_IP.coms_moshi));
        _this.addPoint(new meta_1.WeekField("se_zhouyimoshi", 1762, 2, "周一模式", '', Map_CTL_BJKN_IP.coms_moshi));
        _this.addPoint(new meta_1.WeekField("se_zhouemoshi", 1764, 2, "周二模式", '', Map_CTL_BJKN_IP.coms_moshi));
        _this.addPoint(new meta_1.WeekField("se_zhousanmoshi", 1766, 2, "周三模式", '', Map_CTL_BJKN_IP.coms_moshi));
        _this.addPoint(new meta_1.WeekField("se_zhousimoshi", 1768, 2, "周四模式", '', Map_CTL_BJKN_IP.coms_moshi));
        _this.addPoint(new meta_1.WeekField("se_zhouwumoshi", 1770, 2, "周五模式", '', Map_CTL_BJKN_IP.coms_moshi));
        _this.addPoint(new meta_1.WeekField("se_zhouliumoshi", 1772, 2, "周六模式", '', Map_CTL_BJKN_IP.coms_moshi));
        _this.addPoint(new meta_1.StartStopField("se_richangmoshishiduan1-qidongshijian", 1774, 2, "日常模式  时段1-启动时间"));
        _this.addPoint(new meta_1.StartStopField("se_richangmoshishiduan1-tingzhishijian", 1776, 2, "日常模式  时段1-停止时间"));
        //this.addPoint(new BaseInfoField("se_richangmoshishiduan1-shiduanyouxiao", 1778, 2, "日常模式  时段1-时段有效", '', Map_CTL_BJKN_IP.coms_valid));
        _this.addPoint(new meta_1.StartStopField("se_richangmoshishiduan2-qidongshijian", 1780, 2, "日常模式  时段2-启动时间"));
        _this.addPoint(new meta_1.StartStopField("se_richangmoshishiduan2-tingzhishijian", 1782, 2, "日常模式  时段2-停止时间"));
        //this.addPoint(new BaseInfoField("se_richangmoshishiduan2-shiduanyouxiao", 1784, 2, "日常模式  时段2-时段有效", '', Map_CTL_BJKN_IP.coms_valid));
        _this.addPoint(new meta_1.StartStopField("se_richangmoshishiduan3-qidongshijian", 1786, 2, "日常模式  时段3-启动时间"));
        _this.addPoint(new meta_1.StartStopField("se_richangmoshishiduan3-tingzhishijian", 1788, 2, "日常模式  时段3-停止时间"));
        // this.addPoint(new BaseInfoField("se_richangmoshishiduan3-shiduanyouxiao", 1790, 2, "日常模式  时段3-时段有效", '', Map_CTL_BJKN_IP.coms_valid));
        _this.addPoint(new meta_1.StartStopField("se_richangmoshishiduan4-qidongshijian", 1792, 2, "日常模式  时段4-启动时间"));
        _this.addPoint(new meta_1.StartStopField("se_richangmoshishiduan4-tingzhishijian", 1794, 2, "日常模式  时段4-停止时间"));
        // this.addPoint(new BaseInfoField("se_richangmoshishiduan4-shiduanyouxiao", 1796, 2, "日常模式  时段4-时段有效", '', Map_CTL_BJKN_IP.coms_valid));
        _this.addPoint(new meta_1.StartStopField("se_richangmoshishiduan5-qidongshijian", 1798, 2, "日常模式  时段5-启动时间"));
        _this.addPoint(new meta_1.StartStopField("se_richangmoshishiduan5-tingzhishijian", 1800, 2, "日常模式  时段5-停止时间"));
        // this.addPoint(new BaseInfoField("se_richangmoshishiduan5-shiduanyouxiao", 1802, 2, "日常模式  时段5-时段有效", '', Map_CTL_BJKN_IP.coms_valid));
        _this.addPoint(new meta_1.StartStopField("se_richangmoshishiduan6-qidongshijian", 1804, 2, "日常模式  时段6-启动时间"));
        _this.addPoint(new meta_1.StartStopField("se_richangmoshishiduan6-tingzhishijian", 1806, 2, "日常模式  时段6-停止时间"));
        // this.addPoint(new BaseInfoField("se_richangmoshishiduan6-shiduanyouxiao", 1808, 2, "日常模式  时段6-时段有效", '', Map_CTL_BJKN_IP.coms_valid));
        _this.addPoint(new meta_1.StartStopField("se_teshumoshishiduan1-qidongshijian", 1810, 2, "特殊模式  时段1-启动时间"));
        _this.addPoint(new meta_1.StartStopField("se_teshumoshishiduan1-tingzhishijian", 1812, 2, "特殊模式  时段1-停止时间"));
        // this.addPoint(new BaseInfoField("se_teshumoshishiduan1-shiduanyouxiao", 1814, 2, "特殊模式  时段1-时段有效", '', Map_CTL_BJKN_IP.coms_valid));
        _this.addPoint(new meta_1.StartStopField("se_teshumoshishiduan2-qidongshijian", 1816, 2, "特殊模式  时段2-启动时间"));
        _this.addPoint(new meta_1.StartStopField("se_teshumoshishiduan2-tingzhishijian", 1818, 2, "特殊模式  时段2-停止时间"));
        // this.addPoint(new BaseInfoField("se_teshumoshishiduan2-shiduanyouxiao", 1820, 2, "特殊模式  时段2-时段有效", '', Map_CTL_BJKN_IP.coms_valid));
        _this.addPoint(new meta_1.StartStopField("se_teshumoshishiduan3-qidongshijian", 1822, 2, "特殊模式  时段3-启动时间"));
        _this.addPoint(new meta_1.StartStopField("se_teshumoshishiduan3-tingzhishijian", 1824, 2, "特殊模式  时段3-停止时间"));
        // this.addPoint(new BaseInfoField("se_teshumoshishiduan3-shiduanyouxiao", 1826, 2, "特殊模式  时段3-时段有效", '', Map_CTL_BJKN_IP.coms_valid));
        _this.addPoint(new meta_1.StartStopField("se_teshumoshishiduan4-qidongshijian", 1828, 2, "特殊模式  时段4-启动时间"));
        _this.addPoint(new meta_1.StartStopField("se_teshumoshishiduan4-tingzhishijian", 1830, 2, "特殊模式  时段4-停止时间"));
        // this.addPoint(new BaseInfoField("se_teshumoshishiduan4-shiduanyouxiao", 1832, 2, "特殊模式  时段4-时段有效", '', Map_CTL_BJKN_IP.coms_valid));
        _this.addPoint(new meta_1.StartStopField("se_teshumoshishiduan5-qidongshijian", 1834, 2, "特殊模式  时段5-启动时间"));
        _this.addPoint(new meta_1.StartStopField("se_teshumoshishiduan5-tingzhishijian", 1836, 2, "特殊模式  时段5-停止时间"));
        // this.addPoint(new BaseInfoField("se_teshumoshishiduan5-shiduanyouxiao", 1838, 2, "特殊模式  时段5-时段有效", '', Map_CTL_BJKN_IP.coms_valid));
        _this.addPoint(new meta_1.StartStopField("se_teshumoshishiduan6-qidongshijian", 1840, 2, "特殊模式  时段6-启动时间"));
        _this.addPoint(new meta_1.StartStopField("se_teshumoshishiduan6-tingzhishijian", 1842, 2, "特殊模式  时段6-停止时间"));
        return _this;
        // this.addPoint(new BaseInfoField("se_teshumoshishiduan6-shiduanyouxiao", 1844, 2, "特殊模式  时段6-时段有效", '', Map_CTL_BJKN_IP.coms_valid));
        // this.addPoint(new SettingField("se_richangmoshishiduan1-zhukongcanshu1", 1846, 2, "日常模式  时段1-主控参数1"));
        // this.addPoint(new SettingField("se_richangmoshishiduan1-zhukongcanshu2", 1848, 2, "日常模式  时段1-主控参数2"));
        // this.addPoint(new SettingField("se_richangmoshishiduan1-zhukongcanshu3", 1850, 2, "日常模式  时段1-主控参数3"));
        // this.addPoint(new SettingField("se_richangmoshishiduan1-zhukongcanshu4", 1852, 2, "日常模式  时段1-主控参数4"));
        // this.addPoint(new SettingField("se_richangmoshishiduan2-zhukongcanshu1", 1854, 2, "日常模式  时段2-主控参数1"));
        // this.addPoint(new SettingField("se_richangmoshishiduan2-zhukongcanshu2", 1856, 2, "日常模式  时段2-主控参数2"));
        // this.addPoint(new SettingField("se_richangmoshishiduan2-zhukongcanshu3", 1858, 2, "日常模式  时段2-主控参数3"));
        // this.addPoint(new SettingField("se_richangmoshishiduan2-zhukongcanshu4", 1860, 2, "日常模式  时段2-主控参数4"));
        // this.addPoint(new SettingField("se_richangmoshishiduan3-zhukongcanshu1", 1862, 2, "日常模式  时段3-主控参数1"));
        // this.addPoint(new SettingField("se_richangmoshishiduan3-zhukongcanshu2", 1864, 2, "日常模式  时段3-主控参数2"));
        // this.addPoint(new SettingField("se_richangmoshishiduan3-zhukongcanshu3", 1866, 2, "日常模式  时段3-主控参数3"));
        // this.addPoint(new SettingField("se_richangmoshishiduan3-zhukongcanshu4", 1868, 2, "日常模式  时段3-主控参数4"));
        // this.addPoint(new SettingField("se_richangmoshishiduan4-zhukongcanshu1", 1870, 2, "日常模式  时段4-主控参数1"));
        // this.addPoint(new SettingField("se_richangmoshishiduan4-zhukongcanshu2", 1872, 2, "日常模式  时段4-主控参数2"));
        // this.addPoint(new SettingField("se_richangmoshishiduan4-zhukongcanshu3", 1874, 2, "日常模式  时段4-主控参数3"));
        // this.addPoint(new SettingField("se_richangmoshishiduan4-zhukongcanshu4", 1876, 2, "日常模式  时段4-主控参数4"));
        // this.addPoint(new SettingField("se_richangmoshishiduan5-zhukongcanshu1", 1878, 2, "日常模式  时段5-主控参数1"));
        // this.addPoint(new SettingField("se_richangmoshishiduan5-zhukongcanshu2", 1880, 2, "日常模式  时段5-主控参数2"));
        // this.addPoint(new SettingField("se_richangmoshishiduan5-zhukongcanshu3", 1882, 2, "日常模式  时段5-主控参数3"));
        // this.addPoint(new SettingField("se_richangmoshishiduan5-zhukongcanshu4", 1884, 2, "日常模式  时段5-主控参数4"));
        // this.addPoint(new SettingField("se_richangmoshishiduan6-zhukongcanshu1", 1886, 2, "日常模式  时段6-主控参数1"));
        // this.addPoint(new SettingField("se_richangmoshishiduan6-zhukongcanshu2", 1888, 2, "日常模式  时段6-主控参数2"));
        // this.addPoint(new SettingField("se_richangmoshishiduan6-zhukongcanshu3", 1890, 2, "日常模式  时段6-主控参数3"));
        // this.addPoint(new SettingField("se_richangmoshishiduan6-zhukongcanshu4", 1892, 2, "日常模式  时段6-主控参数4"));
        // this.addPoint(new SettingField("se_teshumoshishiduan1-zhukongcanshu1", 1894, 2, "特殊模式  时段1-主控参数1"));
        // this.addPoint(new SettingField("se_teshumoshishiduan1-zhukongcanshu2", 1896, 2, "特殊模式  时段1-主控参数2"));
        // this.addPoint(new SettingField("se_teshumoshishiduan1-zhukongcanshu3", 1898, 2, "特殊模式  时段1-主控参数3"));
        // this.addPoint(new SettingField("se_teshumoshishiduan1-zhukongcanshu4", 1900, 2, "特殊模式  时段1-主控参数4"));
        // this.addPoint(new SettingField("se_teshumoshishiduan2-zhukongcanshu1", 1902, 2, "特殊模式  时段2-主控参数1"));
        // this.addPoint(new SettingField("se_teshumoshishiduan2-zhukongcanshu2", 1904, 2, "特殊模式  时段2-主控参数2"));
        // this.addPoint(new SettingField("se_teshumoshishiduan2-zhukongcanshu3", 1906, 2, "特殊模式  时段2-主控参数3"));
        // this.addPoint(new SettingField("se_teshumoshishiduan2-zhukongcanshu4", 1908, 2, "特殊模式  时段2-主控参数4"));
        // this.addPoint(new SettingField("se_teshumoshishiduan3-zhukongcanshu1", 1910, 2, "特殊模式  时段3-主控参数1"));
        // this.addPoint(new SettingField("se_teshumoshishiduan3-zhukongcanshu2", 1912, 2, "特殊模式  时段3-主控参数2"));
        // this.addPoint(new SettingField("se_teshumoshishiduan3-zhukongcanshu3", 1914, 2, "特殊模式  时段3-主控参数3"));
        // this.addPoint(new SettingField("se_teshumoshishiduan3-zhukongcanshu4", 1916, 2, "特殊模式  时段3-主控参数4"));
        // this.addPoint(new SettingField("se_teshumoshishiduan4-zhukongcanshu1", 1918, 2, "特殊模式  时段4-主控参数1"));
        // this.addPoint(new SettingField("se_teshumoshishiduan4-zhukongcanshu2", 1920, 2, "特殊模式  时段4-主控参数2"));
        // this.addPoint(new SettingField("se_teshumoshishiduan4-zhukongcanshu3", 1922, 2, "特殊模式  时段4-主控参数3"));
        // this.addPoint(new SettingField("se_teshumoshishiduan4-zhukongcanshu4", 1924, 2, "特殊模式  时段4-主控参数4"));
        // this.addPoint(new SettingField("se_teshumoshishiduan5-zhukongcanshu1", 1926, 2, "特殊模式  时段5-主控参数1"));
        // this.addPoint(new SettingField("se_teshumoshishiduan5-zhukongcanshu2", 1928, 2, "特殊模式  时段5-主控参数2"));
        // this.addPoint(new SettingField("se_teshumoshishiduan5-zhukongcanshu3", 1930, 2, "特殊模式  时段5-主控参数3"));
        // this.addPoint(new SettingField("se_teshumoshishiduan5-zhukongcanshu4", 1932, 2, "特殊模式  时段5-主控参数4"));
        // this.addPoint(new SettingField("se_teshumoshishiduan6-zhukongcanshu1", 1934, 2, "特殊模式  时段6-主控参数1"));
        // this.addPoint(new SettingField("se_teshumoshishiduan6-zhukongcanshu2", 1936, 2, "特殊模式  时段6-主控参数2"));
        // this.addPoint(new SettingField("se_teshumoshishiduan6-zhukongcanshu3", 1938, 2, "特殊模式  时段6-主控参数3"));
        // this.addPoint(new SettingField("se_teshumoshishiduan6-zhukongcanshu4", 1940, 2, "特殊模式  时段6-主控参数4"));
        // this.addPoint(new SettingField("se_gonggongcanshu1", 1942, 2, "公共参数1"));
        // this.addPoint(new SettingField("se_gonggongcanshu2", 1944, 2, "公共参数2"));
        // this.addPoint(new SettingField("se_gonggongcanshu3", 1946, 2, "公共参数3"));
        // this.addPoint(new SettingField("se_gonggongcanshu4", 1948, 2, "公共参数4"));
        // this.addPoint(new SettingField("se_gonggongcanshu5", 1950, 2, "公共参数5"));
        // this.addPoint(new SettingField("se_gonggongcanshu6", 1952, 2, "公共参数6"));
        // this.addPoint(new SettingField("se_gonggongcanshu7", 1954, 2, "公共参数7"));
        // this.addPoint(new SettingField("se_gonggongcanshu8", 1956, 2, "公共参数8"));
        // this.addPoint(new SettingField("se_gonggongcanshu9", 1958, 2, "公共参数9"));
        // this.addPoint(new SettingField("se_gonggongcanshu10", 1960, 2, "公共参数10"));
        // this.addPoint(new SettingField("se_gonggongcanshu11", 1962, 2, "公共参数11"));
        // this.addPoint(new SettingField("se_gonggongcanshu12", 1964, 2, "公共参数12"));
        // this.addPoint(new SettingField("se_gonggongcanshu13", 1966, 2, "公共参数13"));
        // this.addPoint(new SettingField("se_gonggongcanshu14", 1968, 2, "公共参数14"));
        // this.addPoint(new SettingField("se_gonggongcanshu15", 1970, 2, "公共参数15"));
        // this.addPoint(new SettingField("se_gonggongcanshu16", 1972, 2, "公共参数16"));
        // this.addPoint(new SettingField("se_gonggongcanshu17", 1974, 2, "公共参数17"));
        // this.addPoint(new SettingField("se_gonggongcanshu18", 1976, 2, "公共参数18"));
        // this.addPoint(new SettingField("se_gonggongcanshu19", 1978, 2, "公共参数19"));
        // this.addPoint(new SettingField("se_gonggongcanshu20", 1980, 2, "公共参数20"));
    }
    return Map_CTL_BJKN_IP;
}(CTL_NJZJ_IP_485_1749_1.Map_CTL_NJZJ_IP_485_1749));
