"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
var SdcSoftDevice_1 = require("../../../../devices/SdcSoftDevice");
var meta_1 = require("../../../../meta/NJZJ/meta");
var meta_2 = require("../../../../meta/NJZJ/http/meta");
var CTL_NJZJ_1 = require("./CTL_NJZJ");
var gfrm_1 = require("@sdcsoft/gfrm");
var comms_1 = require("@sdcsoft/comms");
var CountShowField_1 = require("../../../../meta/CountShowField");
var CTL_NJZJ_2 = require("../../../../devices/CTL/NJZJ/CTL_NJZJ");
var Map_CTL_NJZJ_IP_Http = /** @class */ (function (_super) {
    __extends(Map_CTL_NJZJ_IP_Http, _super);
    function Map_CTL_NJZJ_IP_Http() {
        var _this = _super.call(this) || this;
        _this.addPoint(new meta_1.SystemStatusField(SdcSoftDevice_1.SdcSoftDevice.KEY_POINT_SYSTEM_STATUS, 20, 1, '系统状态', Map_CTL_NJZJ_IP_Http.coms_status, Map_CTL_NJZJ_IP_Http.Commands_Key_System_Ctl, '0602', 1, 2));
        _this.addPoint(new meta_2.RunDaysField(SdcSoftDevice_1.SdcSoftDevice.KEY_POINT_RUN_DAYS, 21, 2, '运行天数', '天'));
        _this.addPoint(new meta_2.BaseInfoField(SdcSoftDevice_1.SdcSoftDevice.KEY_POINT_RUN_HOURS, 23, 1, '运行小时数', '时'));
        _this.addPoint(new meta_2.BaseInfoField(SdcSoftDevice_1.SdcSoftDevice.KEY_POINT_POWER, 24, 1, '燃料类型', '', Map_CTL_NJZJ_IP_Http.coms_power));
        _this.addPoint(new meta_2.BaseInfoField(SdcSoftDevice_1.SdcSoftDevice.KEY_POINT_MEDIA, 25, 1, '介质类型', '', Map_CTL_NJZJ_IP_Http.coms_media));
        _this.addPoint(new meta_2.BaseInfoField('ba_guolushuiweizhuangtai', 26, 1, '锅炉液位状态', '', Map_CTL_NJZJ_IP_Http.coms_level));
        _this.addPoint(new meta_2.BaseInfoField('ba_shuixiangshuiweizhuangtai', 27, 1, '水箱液位状态', '', Map_CTL_NJZJ_IP_Http.coms_level));
        _this.addPoint(new CountShowField_1.CountShowField(comms_1.GroupKeys.KEY_BASE, SdcSoftDevice_1.SdcSoftDevice.KEY_POINT_JIA_RE_ZU, '投入加热组', ''));
        _this.addPoint(new meta_2.BaseInfoField('ba_guoluyalizhuangtai', 28, 1, '锅炉压力状态', '', Map_CTL_NJZJ_IP_Http.coms_yalistatus));
        _this.addPoint(new meta_2.BaseInfoField('ba_moshibianhao', 29, 1, '模式编号', ''));
        _this.addPoint(new meta_2.BaseInfoField('ba_fangdongkaiguan', 30, 1, '防冻开关', '', Map_CTL_NJZJ_IP_Http.coms_open_close));
        _this.addPoint(new meta_2.BaseInfoField('ba_qipao1shuiweizhuangtai', 31, 1, '汽包1水位状态', '', Map_CTL_NJZJ_IP_Http.coms_qipao_level));
        _this.addPoint(new meta_2.BaseInfoField('ba_qipao1shuiweizhuangtai', 801, 1, '汽包2水位状态', '', Map_CTL_NJZJ_IP_Http.coms_qipao_level));
        _this.addPoint(new meta_2.ExceptionField('ex_paiyanwendugaobaojing', 32, 1, '排烟温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_lushuiwendugaobaojing', 33, 1, '炉水温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_chukouwendugaobaojing', 34, 1, '出口温度高报警'));
        _this.addPoint(new meta_2.ExceptionField(gfrm_1.GroupFieldsRelationalMapping.KEY_Expt_ChaoYa, 35, 1, '超压报警'));
        _this.addPoint(new meta_2.ExceptionField(gfrm_1.GroupFieldsRelationalMapping.KEY_Expt_JiXianDiShuiWei, 36, 1, '极限低水位报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_dishuiweibaojing', 37, 1, '低水位报警'));
        _this.addPoint(new meta_2.ExceptionField(gfrm_1.GroupFieldsRelationalMapping.KEY_Expt_JiXianGaoShuiWei, 38, 1, '高水位报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_shuiweixinhaoluojicuobaojing', 39, 1, '水位信号逻辑错报警'));
        _this.addPoint(new meta_2.ExceptionField(gfrm_1.GroupFieldsRelationalMapping.KEY_Expt_LuBiChaoWen, 40, 1, '炉壁温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_fuyazhengqiwendugaobaojing', 41, 1, '负压蒸汽温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_ranshaoqiguzhangbaojing', 42, 1, '燃烧器故障报警'));
        _this.addPoint(new meta_2.ExceptionField(gfrm_1.GroupFieldsRelationalMapping.KEY_Expt_RanQiXieLou, 43, 1, '燃气泄漏报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_ranqiyalidibaojing', 44, 1, '燃气压力低报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_ranqiyaliyichangbaojing', 45, 1, '燃气压力异常报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_ranqiyaligaobaojing', 46, 1, '燃气压力高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_jishuibianpinqiguzhangbaojing', 47, 1, '给水变频器故障报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_xunhuanbianpinqiguzhangbaojing', 48, 1, '循环变频器故障报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_yinfengbianpinqiguzhangbaojing', 49, 1, '引风变频器故障报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_gufengbianpinqiguzhangbaojing', 50, 1, '鼓风变频器故障报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_ecigufengbianpinqiguzhangbaojing', 51, 1, '二次鼓风变频器故障报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_lupaibianpinqiguzhangbaojing', 52, 1, '炉排变频器故障报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_addshuibengguzhangbaojing', 53, 1, '给水泵故障报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_xunhuanbengguzhangbaojing', 54, 1, '循环泵故障报警'));
        _this.addPoint(new meta_2.ExceptionField(gfrm_1.GroupFieldsRelationalMapping.KEY_Expt_QianYa, 55, 1, '欠压报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_didianyabaojing', 56, 1, '低电压报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_gaodianyabaojing', 57, 1, '高电压报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_quexiangbaojing', 58, 1, '缺相报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_loudianbaojing', 59, 1, '漏电报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_biansongqiguoyabaohu', 60, 1, '变送器过压保护'));
        _this.addPoint(new meta_2.ExceptionField('ex_guanjiancanshuyichang', 61, 1, '关键参数异常'));
        _this.addPoint(new meta_2.ExceptionField('ex_shedingcanshuyichang', 62, 1, '设定参数异常'));
        _this.addPoint(new meta_2.ExceptionField('ex_shizhongguzhang', 63, 1, '时钟故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_cunchuqiguzhang', 64, 1, '存储器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_waibuliansuobaojing', 65, 1, '外部连锁报警'));
        _this.addPoint(new meta_2.ExceptionField(gfrm_1.GroupFieldsRelationalMapping.KEY_Expt_JiXianDiShuiWei, 66, 1, '缺油报警'), 'ex_queyoubaojing');
        _this.addPoint(new meta_2.ExceptionField('ex_diyouweibaojing', 67, 1, '低油位报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_bentipaiyanwendugaobaojing', 68, 1, '本体排烟温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_bianpinqiguzhangbaojing', 69, 1, '变频器故障报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_meishuiwendugaobaojing', 70, 1, '媒水温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_1haoguoluguzhang', 71, 1, '1号锅炉故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_2haoguoluguzhang', 72, 1, '2号锅炉故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_3haoguoluguzhang', 73, 1, '3号锅炉故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_4haoguoluguzhang', 74, 1, '4号锅炉故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_5haoguoluguzhang', 75, 1, '5号锅炉故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_6haoguoluguzhang', 76, 1, '6号锅炉故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_7haoguoluguzhang', 77, 1, '7号锅炉故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_8haoguoluguzhang', 78, 1, '8号锅炉故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_bushuibianpinqiguzhangbaojing', 79, 1, '补水变频器故障报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_shuiliukaiguanbaohubaojing', 80, 1, '水流开关保护报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_rukouwendudibaojing', 81, 1, '入口温度低报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_xunhuanbengbianpinqiguzhang', 82, 1, '循环泵变频器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_ecixunhuanbengbianpinqiguzhang', 83, 1, '二次循环泵变频器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_reshuibengbianpinqiguzhang', 84, 1, '热水泵变频器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_buyoubengbianpinqiguzhang', 85, 1, '补油泵变频器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_ecigufengbianpinqiguzhang', 86, 1, '二次鼓风变频器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_songliaojibianpinqiguzhang', 87, 1, '送料机变频器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_zhenkongbengbianpinqiguzhang', 88, 1, '真空泵变频器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_lengningbengbianpinqiguzhang', 89, 1, '冷凝泵变频器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_addshuibengguzhang', 90, 1, '补水泵故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_buyoubengguzhang', 91, 1, '补油泵故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_lengningbengguzhang', 92, 1, '冷凝泵故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_reshuibengguzhang', 93, 1, '热水泵故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_zhenkongbengguzhang', 94, 1, '真空泵故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_ecixunhuanbengguzhang', 95, 1, '二次循环泵故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu1xunhuanbengguzhang', 96, 1, '回路1循环泵故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu2xunhuanbengguzhang', 97, 1, '回路2循环泵故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu3xunhuanbengguzhang', 98, 1, '回路3循环泵故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu4xunhuanbengguzhang', 99, 1, '回路4循环泵故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu5xunhuanbengguzhang', 100, 1, '回路5循环泵故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu1wendugaobaojing', 101, 1, '回路1温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu2wendugaobaojing', 102, 1, '回路2温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu3wendugaobaojing', 103, 1, '回路3温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu4wendugaobaojing', 104, 1, '回路4温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu5wendugaobaojing', 105, 1, '回路5温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan1wendugaobaojing', 106, 1, '盘管1温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan2wendugaobaojing', 107, 1, '盘管2温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan3wendugaobaojing', 108, 1, '盘管3温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan4wendugaobaojing', 109, 1, '盘管4温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan5wendugaobaojing', 110, 1, '盘管5温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan6wendugaobaojing', 111, 1, '盘管6温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan7wendugaobaojing', 112, 1, '盘管7温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan8wendugaobaojing', 113, 1, '盘管8温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan9wendugaobaojing', 114, 1, '盘管9温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan10wendugaobaojing', 115, 1, '盘管10温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_shanzhengguanchaoyabaojing', 116, 1, '闪蒸罐超压报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_lengningguanchaoyabaojing', 117, 1, '冷凝罐超压报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_pengzhangguanchaoyabaojing', 118, 1, '膨胀罐超压报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_shanzhengguanyeweigaobaojing', 119, 1, '闪蒸罐液位高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_shanzhengguanyeweidibaojing', 120, 1, '闪蒸罐液位低报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_lengningguanyeweigaobaojing', 121, 1, '冷凝罐液位高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_lengningguanyeweidibaojing', 122, 1, '冷凝罐液位低报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_pengzhangguanyeweigaobaojing', 123, 1, '膨胀罐液位高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_pengzhangguanyeweidibaojing', 124, 1, '膨胀罐液位低报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_jinchukouyachadibaojing', 125, 1, '进出口压差低报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_jinchukouyachagaobaojing', 126, 1, '进出口压差高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_zhenkongyalibuzubaojing', 127, 1, '真空压力不足报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_jinchukouwenchadibaojing', 128, 1, '进出口温差低报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_jinchukouwenchagaobaojing', 129, 1, '进出口温差高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_guoluhuohuiluchukouyaligaobaojing', 130, 1, '出口压力高报警（锅炉或回路）'));
        _this.addPoint(new meta_2.ExceptionField('ex_guoluhuohuiluchukouyalidibaojing', 131, 1, '出口压力低报警（锅炉或回路）'));
        _this.addPoint(new meta_2.ExceptionField('ex_guoluhuohuilurukouyaligaobaojing', 132, 1, '入口压力高报警（锅炉或回路）'));
        _this.addPoint(new meta_2.ExceptionField('ex_guoluhuohuilurukouyalidibaojing', 133, 1, '入口压力低报警（锅炉或回路）'));
        _this.addPoint(new meta_2.ExceptionField('ex_dongzuofankuiyichangyinfengjiguzhangbaojing', 134, 1, '引风机故障报警（动作反馈异常）'));
        _this.addPoint(new meta_2.ExceptionField('ex_cainuanchukouwendugaobaojing', 135, 1, '采暖出口温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_reshuichukouwendugaobaojing', 136, 1, '热水出口温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_jinkouwendugaobaojing', 137, 1, '进口温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_pengzhangguanwendugaobaojing', 138, 1, '膨胀罐温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_guodianliubaojing', 139, 1, '过电流报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_jishuiyaligaobaojing', 140, 1, '给水压力高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_jienengqichukouyanwengaobaojing', 141, 1, '节能器出口烟温高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_lengningqichukouyanwengaobaojing', 142, 1, '冷凝器出口烟温高报警'));
        _this.addPoint(new meta_2.ExceptionField(gfrm_1.GroupFieldsRelationalMapping.KEY_Expt_ChuKouWenDuChaoGao, 143, 1, '出水温度高报警'), 'ex_chushuiwendugaobaojing');
        _this.addPoint(new meta_2.ExceptionField('ex_gaowenbaohuwendugaobaojing', 144, 1, '高温保护温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_youwengaobaojing', 145, 1, '油温高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_wenchagaobaojing', 146, 1, '温差高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_shuibengguozaibaojing', 147, 1, '水泵过载报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_jiarezuguozaibaojing', 148, 1, '加热组过载报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_churexunhuanbengguzhangbaojing', 149, 1, '储热循环泵故障报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_yandaodiefaguzhang', 150, 1, '烟道蝶阀故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_nengliangshezhiwendugaobaojing', 151, 1, '能量设置温度高报警'));
        //
        _this.addPoint(new meta_2.ExceptionField('ex_zhengqiwendugaobaojing', 152, 1, '蒸汽温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_shuixiangwendugaobaojing', 153, 1, '水箱温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_1#guodianliubaojing', 154, 1, '1#过电流报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_2#guodianliubaojing', 155, 1, '2#过电流报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_3#guodianliubaojing', 156, 1, '3#过电流报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_4#guodianliubaojing', 157, 1, '4#过电流报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_5#guodianliubaojing', 158, 1, '5#过电流报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_gufengjiguzhangbaojing', 159, 1, '鼓风机故障报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_jiezhigaowenbaojing', 160, 1, '介质高温报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_jiezhidiwenbaojing', 161, 1, '介质低温报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_kongdiaoxitongwendugaobaojing', 162, 1, '空调系统温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_dinuanxitongwendugaobaojing', 163, 1, '地暖系统温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_yongchixitongwendugaobaojing', 164, 1, '泳池系统温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_fengyagaobaojing', 165, 1, '风压高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_fengyadibaojing', 166, 1, '风压低报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_shuixiangshuiweixinhaoluojicuobaojing', 167, 1, '水箱水位信号逻辑错报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_PHzhigaobaojing', 168, 1, 'PH值高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_PHzhidibaojing', 179, 1, 'PH值低报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_chaowenbaojing1', 170, 1, '超温报警1'));
        _this.addPoint(new meta_2.ExceptionField('ex_chaowenbaojing2', 171, 1, '超温报警2'));
        _this.addPoint(new meta_2.ExceptionField('ex_chaowenbaojing3', 172, 1, '超温报警3'));
        _this.addPoint(new meta_2.ExceptionField('ex_jienengqijinkouyanwengaobaojing', 173, 1, '节能器进口烟温高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_shuixiangqueshuibaojing', 174, 1, '水箱缺水报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_1#morukuozhanmokuaitongxunyichang', 175, 1, '1#模入扩展模块通讯异常'));
        _this.addPoint(new meta_2.ExceptionField('ex_2#morukuozhanmokuaitongxunyichang', 176, 1, '2#模入扩展模块通讯异常'));
        _this.addPoint(new meta_2.ExceptionField('ex_3#morukuozhanmokuaitongxunyichang', 177, 1, '3#模入扩展模块通讯异常'));
        _this.addPoint(new meta_2.ExceptionField('ex_4#morukuozhanmokuaitongxunyichang', 178, 1, '4#模入扩展模块通讯异常'));
        _this.addPoint(new meta_2.ExceptionField('ex_reshuixunhuanbengbianpinqiguzhang', 179, 1, '热水循环泵变频器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_yuanshuixiangyeweidibaojing', 180, 1, '原水箱液位低报警'));
        //------------------------------------------------报警扩展-------------------------------------------------
        _this.addPoint(new meta_2.ExceptionField('ex_a1baojing', 881, 1, '原水泵出口压力高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_a2baojing', 882, 1, '高压泵出口压力高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_a3baojing', 883, 1, '点火失败报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_a4baojing', 884, 1, '原水泵变频器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_a5baojing', 885, 1, '循环泵过载报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_a6baojing', 886, 1, '二次循环泵过载报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_a7baojing', 887, 1, '进水温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_a8baojing', 888, 1, '鼓风机过载报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_a9baojing', 889, 1, '汽包1极限低水位报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_b1baojing', 890, 1, '汽包1低水位报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_b2baojing', 891, 1, '汽包1高水位报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_b3baojing', 892, 1, '汽包1水位信号逻辑错报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_b4baojing', 893, 1, '汽包2极限低水位报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_b5baojing', 894, 1, '汽包2低水位报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_b6baojing', 895, 1, '汽包2高水位报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_b7baojing', 896, 1, '汽包2水位信号逻辑错报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_b8baojing', 897, 1, '熔盐槽温度高报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_b9baojing', 898, 1, '熔盐槽液位低报警'));
        _this.addPoint(new meta_2.ExceptionField('ex_c1baojing', 899, 1, '炉膛温度高报警'));
        //故障
        _this.addPoint(new meta_2.ExceptionField('ex_paiyanwenduchuanganqiguzhang', 182, 1, '排烟温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_lushuiwenduchuanganqiguzhang', 183, 1, '炉水温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_chukouwenduchuanganqiguzhang', 184, 1, '出口温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_rukouwenduchuanganqiguzhang', 185, 1, '入口温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jienengqichukouwenduchuanganqiguzhang', 186, 1, '节能器出口温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jienengqirukouwenduchuanganqiguzhang', 187, 1, '节能器入口温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jishuiwenduchuanganqiguzhang', 188, 1, '给水温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_lutangwenduchuanganqiguzhang', 189, 1, '炉膛温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_lutangchukouwenduchuanganqiguzhang', 190, 1, '炉膛出口温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_lubiwenduchuanganqiguzhang', 191, 1, '炉壁温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_ranliaowenduchuanganqiguzhang', 192, 1, '燃料温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_refengwenduchuanganqiguzhang', 193, 1, '热风温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_fuyazhengqiwenduchuanganqiguzhang', 194, 1, '负压蒸汽温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_guorezhengqiwenduchuanganqiguzhang', 195, 1, '过热蒸汽温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu1wenduchuanganqiguzhang', 196, 1, '回路1温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu2wenduchuanganqiguzhang', 197, 1, '回路2温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu3wenduchuanganqiguzhang', 198, 1, '回路3温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu4wenduchuanganqiguzhang', 199, 1, '回路4温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu5wenduchuanganqiguzhang', 200, 1, '回路5温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_shiwaiwenduchuanganqiguzhang', 201, 1, '室外温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_zhengqiyalichuanganqiguzhang', 202, 1, '蒸汽压力变送器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jishuiyalichuanganqiguzhang', 203, 1, '给水压力传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_chukouyalichuanganqiguzhang', 204, 1, '出口压力传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_rukouyalichuanganqiguzhang', 205, 1, '入口压力传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_lutangyalichuanganqiguzhang', 206, 1, '炉膛压力传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_lutangchukouyalichuanganqiguzhang', 207, 1, '炉膛出口压力传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_ranqiyalichuanganqiguzhang', 208, 1, '燃气压力传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_yicifengyachuanganqiguzhang', 209, 1, '一次风压传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_ecifengyachuanganqiguzhang', 210, 1, '二次风压传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_ranliaoliangchuanganqiguzhang', 211, 1, '燃料量传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_zhengqiliuliangchuanganqiguzhang', 212, 1, '蒸汽流量传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jishuiliuliangchuanganqiguzhang', 213, 1, '给水流量传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_xunhuanliuliangchuanganqiguzhang', 214, 1, '循环流量传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_bushuiliuliangchuanganqiguzhang', 215, 1, '补水流量传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_guoluyeweichuanganqiguzhang', 216, 1, '锅炉液位传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_shuixiangyeweichuanganqiguzhang', 217, 1, '水箱液位传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_paiyanyanghanliangchuanganqiguzhang', 218, 1, '排烟氧含量传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_lupaisudufankuichuanganqiguzhang', 219, 1, '炉排速度反馈传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_yinfengshuchufankuichuanganqiguzhang', 220, 1, '引风输出反馈传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_gufengshuchufankuichuanganqiguzhang', 221, 1, '鼓风输出反馈传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jishuishuchufankuichuanganqiguzhang', 222, 1, '给水输出反馈传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_meishuiwenduchuanganqiguzhang', 223, 1, '媒水温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_shuixiangwenduchuanganqiguzhang', 224, 1, '水箱温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_pengzhangguanyeweichuanganqiguzhang', 225, 1, '膨胀罐液位传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_shanzhengguanyeweichuanganqiguzhang', 226, 1, '闪蒸罐液位传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_lengningyeguanyeweichuanganqiguzhang', 227, 1, '冷凝液罐液位传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_chuguanyeweichuanganqiguzhang', 228, 1, '储罐液位传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_pengzhangguanwenduchuanganqiguzhang', 229, 1, '膨胀罐温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_shanzhengguanwenduchuanganqiguzhang', 230, 1, '闪蒸罐温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_lengningyeguanwenduchuanganqiguzhang', 231, 1, '冷凝液罐温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_chuguanwenduchuanganqiguzhang', 232, 1, '储罐温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_guoluyalichuanganqiguzhang', 233, 1, '锅炉压力传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_guorezhengqiyalichuanganqiguzhang', 234, 1, '过热蒸汽压力传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_paiyanchuyalichuanganqiguzhang', 235, 1, '排烟处压力传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_fengshifengyachuanganqiguzhang', 236, 1, '风室风压传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_yinfengjidianliuchuanganqiguzhang', 237, 1, '引风机电流传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_gufengjidianliuchuanganqiguzhang', 238, 1, '鼓风机电流传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jiliaojisudufankuichuanganqiguzhang', 239, 1, '给料机速度反馈传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan1wenduchuanganqiguzhang', 240, 1, '盘管1温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan2wenduchuanganqiguzhang', 241, 1, '盘管2温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan3wenduchuanganqiguzhang', 242, 1, '盘管3温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan4wenduchuanganqiguzhang', 243, 1, '盘管4温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan5wenduchuanganqiguzhang', 244, 1, '盘管5温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan6wenduchuanganqiguzhang', 245, 1, '盘管6温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan7wenduchuanganqiguzhang', 246, 1, '盘管7温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan8wenduchuanganqiguzhang', 247, 1, '盘管8温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan9wenduchuanganqiguzhang', 248, 1, '盘管9温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_panguan10wenduchuanganqiguzhang', 249, 1, '盘管10温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_cainuanchukouwenduchuanganqiguzhang', 250, 1, '采暖出口温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_reshuichukouwenduchuanganqiguzhang', 251, 1, '热水出口温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jinchukouyachachuanganqiguzhang', 252, 1, '进出口压差传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_1#chukouwenduchuanganqiguzhang', 253, 1, '1#出口温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_2#chukouwenduchuanganqiguzhang', 254, 1, '2#出口温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jienengqichukouyanwenchuanganqiguzhang', 255, 1, '节能器出口烟温传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jienengqijinkouyanwenchuanganqiguzhang', 256, 1, '节能器进口烟温传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_lengningqichukouwendu_shui_chuanganqiguzhang', 257, 1, '冷凝器出口温度（水）传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_lengningqijinkou_shui_chuanganqiguzhang', 258, 1, '冷凝器进口（水）传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_lengningqichukouyanwenchuanganqiguzhang', 259, 1, '冷凝器出口烟温传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_lengningqijinkouyanwenchuanganqiguzhang', 260, 1, '冷凝器进口烟温传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_cainuanjinkouwenduchuanganqiguzhang', 261, 1, '采暖进口温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_reshuijinkouwenduchuanganqiguzhang', 262, 1, '热水进口温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_kongzhixiangwenduchuanganqiguzhang', 263, 1, '控制箱温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_zhenkongyalichuanganqiguzhang', 264, 1, '真空压力传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_chushuiwenduchuanganqiguzhang', 265, 1, '出水温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jinshuiwenduchuanganqiguzhang', 266, 1, '进水温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_youwenjiancechuanganqiguzhang', 267, 1, '油温检测传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_gaowenbaohuchuanganqiguzhang', 268, 1, '高温保护传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_chukouyouwenchuanganqiguzhang', 269, 1, '出口油温传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jinkouyouwenchuanganqiguzhang', 270, 1, '进口油温传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_huanrewenduchuanganqiguzhang', 271, 1, '换热温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_xitongwenduchuanganqiguzhang', 272, 1, '系统温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_nengliangshezhiwenduchuanganqiguzhang', 273, 1, '能量设置温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_zhengqiwenduchuanganqiguzhang', 274, 1, '蒸汽温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_shineiwenduchuanganqiguzhang', 275, 1, '室内温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_1#dianliufankuichuanganqiguzhang', 276, 1, '1#电流反馈传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_2#dianliufankuichuanganqiguzhang', 982, 1, '2#电流反馈传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_3#dianliufankuichuanganqiguzhang', 983, 1, '3#电流反馈传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_4#dianliufankuichuanganqiguzhang', 984, 1, '4#电流反馈传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_5#dianliufankuichuanganqiguzhang', 985, 1, '5#电流反馈传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jiezhiwenduchuanganqiguzhang', 986, 1, '介质温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_xiyuwenduchuanganqiguzhang', 987, 1, '洗浴温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_huanjingwenduchuanganqiguzhang', 988, 1, '环境温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jiezhiyalichuanganqiguzhang', 989, 1, '介质压力传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu1jinkouwenduchuanganqiguzhang', 990, 1, '回路1进口温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu2jinkouwenduchuanganqiguzhang', 991, 1, '回路2进口温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu3jinkouwenduchuanganqiguzhang', 992, 1, '回路3进口温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu4jinkouwenduchuanganqiguzhang', 993, 1, '回路4进口温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_huilu5jinkouwenduchuanganqiguzhang', 994, 1, '回路5进口温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_kongdiaoxitongwenduchuanganqiguzhang', 995, 1, '空调系统温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_dinuanxitongwenduchuanganqiguzhang', 996, 1, '地暖系统温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_yongchixitongwenduchuanganqiguzhang', 997, 1, '泳池系统温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_phzhichuanganqiguzhang', 998, 1, 'PH值传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jiezhi1chuanganqiguzhang', 999, 1, '介质1温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jiezhi2chuanganqiguzhang', 1000, 1, '介质2温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jiezhi3chuanganqiguzhang', 1001, 1, '介质3温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jiezhi4chuanganqiguzhang', 1002, 1, '介质4温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jiezhi5duchuanganqiguang', 1003, 1, '介质5温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_jiezhi6chuanganqiguzhang', 1004, 1, '介质6温度传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_danfengyalichuanganqiguzang', 1005, 1, '氮封压力传感器故障'));
        _this.addPoint(new meta_2.ExceptionField('ex_rongyancaowenduchuanganqiguzhang', 1006, 1, '熔盐槽温度传感器故障'));
        //
        _this.addPoint(new meta_1.MockField('mo_bentipaiyanwendu', 277, 2, '本体排烟温度', '℃'));
        _this.addPoint(new meta_1.MockField(gfrm_1.GroupFieldsRelationalMapping.KEY_MOCK_PaiYanWenDu, 279, 2, '排烟温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_lushuiwendu', 281, 2, '炉水温度', '℃'));
        _this.addPoint(new meta_1.MockField(gfrm_1.GroupFieldsRelationalMapping.KEY_MOCK_ChuKouWenDu, 283, 2, '出口温度', '℃'));
        _this.addPoint(new meta_1.MockField(gfrm_1.GroupFieldsRelationalMapping.KEY_MOCK_HuiLiuWenDu, 285, 2, '入口温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_jienengqichukouwendu', 287, 2, '节能器出口温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_jienengqirukouwendu', 289, 2, '节能器入口温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_jishuiwendu', 291, 2, '给水温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_lutangwendu', 293, 2, '炉膛温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_lutangchukouwendu', 295, 2, '炉膛出口温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_lubiwendu', 297, 2, '炉壁温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_ranliaowendu', 299, 2, '燃料温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_refengwendu', 301, 2, '热风温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_fuyazhengqiwendu', 303, 2, '负压蒸汽温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_guorezhengqiwendu', 305, 2, '过热蒸汽温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_huilu1wendu', 307, 2, '回路1温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_huilu2wendu', 309, 2, '回路2温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_huilu3wendu', 311, 2, '回路3温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_huilu4wendu', 313, 2, '回路4温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_huilu5wendu', 315, 2, '回路5温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_shiwaiwendu', 317, 2, '室外温度', '℃'));
        _this.addPoint(new meta_1.MockField(gfrm_1.GroupFieldsRelationalMapping.KEY_MOCK_ZhengQiYaLi, 319, 2, '蒸汽压力', 'MPa', 100));
        _this.addPoint(new meta_1.MockField('mo_jishuiyali', 321, 2, '给水压力', 'MPa', 100));
        _this.addPoint(new meta_1.MockField('mo_chukouyali', 323, 2, '出口压力', 'MPa', 100));
        _this.addPoint(new meta_1.MockField('mo_rukouyali', 325, 2, '入口压力', 'MPa', 100));
        _this.addPoint(new meta_1.MockField('mo_lutangyali', 327, 2, '炉膛压力', 'Pa'));
        _this.addPoint(new meta_1.MockField('mo_lutangchukouyali', 329, 2, '炉膛出口压力', 'Pa'));
        _this.addPoint(new meta_1.MockField('mo_ranqiyali', 331, 2, '燃气压力', 'KPa'));
        _this.addPoint(new meta_1.MockField('mo_yicifengya', 333, 2, '一次风压', 'KPa'));
        _this.addPoint(new meta_1.MockField('mo_ecifengya', 335, 2, '二次风压', 'KPa'));
        _this.addPoint(new meta_1.MockField('mo_ranliaoliang', 337, 2, '燃料量'));
        _this.addPoint(new meta_1.MockField('mo_zhengqiliuliang', 339, 2, '蒸汽流量'));
        _this.addPoint(new meta_1.MockField('mo_jishuiliuliang', 341, 2, '给水流量'));
        _this.addPoint(new meta_1.MockField('mo_xunhuanliuliang', 343, 2, '循环流量'));
        _this.addPoint(new meta_1.MockField('mo_bushuiliuliang', 345, 2, '补水流量'));
        _this.addPoint(new meta_1.MockField('mo_guoluyewei', 347, 2, '锅炉液位', 'mm'));
        _this.addPoint(new meta_1.MockField('mo_shuixiangyewei', 349, 2, '水箱液位', 'mm'));
        _this.addPoint(new meta_1.MockField('mo_paiyanyanghanliang', 351, 2, '排烟氧含量', '%', 10));
        _this.addPoint(new meta_1.MockField('mo_lupaisudufankui', 353, 2, '炉排速度反馈', '%'));
        _this.addPoint(new meta_1.MockField('mo_yinfengshuchufankui', 355, 2, '引风输出反馈', '%'));
        _this.addPoint(new meta_1.MockField('mo_gufengshuchufankui', 357, 2, '鼓风输出反馈', '%'));
        _this.addPoint(new meta_1.MockField('mo_jishuishuchufankui', 359, 2, '给水输出反馈', '%'));
        _this.addPoint(new meta_1.MockField('mo_meishuiwendu', 361, 2, '媒水温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_shuixiangwendu', 363, 2, '水箱温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_pengzhangguanyewei', 365, 2, '膨胀罐液位', 'mm'));
        _this.addPoint(new meta_1.MockField('mo_shanzhengguanyewei', 367, 2, '闪蒸罐液位', 'mm'));
        _this.addPoint(new meta_1.MockField('mo_lengningyeguanyewei', 369, 2, '冷凝液罐液位', 'mm'));
        _this.addPoint(new meta_1.MockField('mo_chuguanyewei', 371, 2, '储罐液位', 'mm'));
        _this.addPoint(new meta_1.MockField('mo_pengzhangguanwendu', 373, 2, '膨胀罐温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_shanzhengguanwendu', 375, 2, '闪蒸罐温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_lengningyeguanwendu', 377, 2, '冷凝液罐温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_chuguanwendu', 379, 2, '储罐温度', '℃'));
        _this.addPoint(new meta_1.MockField(gfrm_1.GroupFieldsRelationalMapping.KEY_MOCK_ReShuiYaLi, 381, 2, '系统压力（用于承压热水锅炉）', 'MPa', 100), 'mo_xitongyali_yongyuchengyareshuiguolu_');
        _this.addPoint(new meta_1.MockField('mo_guorezhengqiyali', 383, 2, '过热蒸汽压力', 'MPa', 100));
        _this.addPoint(new meta_1.MockField('mo_paiyanchuyali', 385, 2, '排烟处压力', 'Pa'));
        _this.addPoint(new meta_1.MockField('mo_fengshifengya', 387, 2, '风室风压', 'KPa'));
        _this.addPoint(new meta_1.MockField('mo_yinfengjidianliu', 389, 2, '引风机电流', 'A'));
        _this.addPoint(new meta_1.MockField('mo_gufengjidianliu', 391, 2, '鼓风机电流', 'A'));
        _this.addPoint(new meta_1.MockField('mo_jiliaojisudufankui', 393, 2, '给料机速度反馈', '%'));
        _this.addPoint(new meta_1.MockField('mo_panguan1wendu', 395, 2, '盘管1温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_panguan2wendu', 397, 2, '盘管2温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_panguan3wendu', 399, 2, '盘管3温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_panguan4wendu', 401, 2, '盘管4温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_panguan5wendu', 403, 2, '盘管5温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_panguan6wendu', 405, 2, '盘管6温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_panguan7wendu', 407, 2, '盘管7温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_panguan8wendu', 409, 2, '盘管8温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_panguan9wendu', 411, 2, '盘管9温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_panguan10wendu', 413, 2, '盘管10温度', '℃'));
        _this.addPoint(new meta_1.MockField(gfrm_1.GroupFieldsRelationalMapping.KEY_MOCK_CaiNuanChuKouWenDu, 415, 2, '采暖出口温度', '℃'));
        _this.addPoint(new meta_1.MockField(gfrm_1.GroupFieldsRelationalMapping.KEY_MOCK_ShengHuoChuKouWenDu, 417, 2, '热水出口温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_jinchukouyacha', 419, 2, '进出口压差', 'MPa', 100));
        _this.addPoint(new meta_1.MockField('mo_1#chukouwendu', 421, 2, '1#出口温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_2#chukouwendu', 423, 2, '2#出口温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_jienengqichukouyanwen', 425, 2, '节能器出口烟温', '℃'));
        _this.addPoint(new meta_1.MockField('mo_jienengqijinkouyanwen', 427, 2, '节能器进口烟温', '℃'));
        _this.addPoint(new meta_1.MockField('mo_lengningqichukouwendu_shui_', 429, 2, '冷凝器出口温度（水）', '℃'));
        _this.addPoint(new meta_1.MockField('mo_lengningqijinkouwendu_shui_', 431, 2, '冷凝器进口温度（水）', '℃'));
        _this.addPoint(new meta_1.MockField('mo_lengningqichukouyanwen', 433, 2, '冷凝器出口烟温', '℃'));
        _this.addPoint(new meta_1.MockField('mo_lengningqijinkouyanwen', 435, 2, '冷凝器进口烟温', '℃'));
        _this.addPoint(new meta_1.MockField(gfrm_1.GroupFieldsRelationalMapping.KEY_MOCK_CaiNuanHuiLiuWenDu, 437, 2, '采暖进口温度', '℃'));
        _this.addPoint(new meta_1.MockField(gfrm_1.GroupFieldsRelationalMapping.KEY_MOCK_ShengHuoHuiLiuWenDu, 439, 2, '热水进口温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_kongzhixiangwendu', 441, 2, '控制箱温度', '℃'));
        _this.addPoint(new meta_1.MockField(gfrm_1.GroupFieldsRelationalMapping.KEY_MOCK_ReShuiYaLi, 443, 2, '真空压力', 'KPa'));
        _this.addPoint(new meta_1.MockField('mo_chushuiwendu', 445, 2, '出水温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_jinshuiwendu', 447, 2, '进水温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_youwenjiance', 449, 2, '油温检测', '℃'));
        _this.addPoint(new meta_1.MockField('mo_gaowenbaohu', 451, 2, '高温保护', '℃'));
        _this.addPoint(new meta_1.MockField(gfrm_1.GroupFieldsRelationalMapping.KEY_MOCK_ChuKouWenDu, 453, 2, '出口油温', '℃'), 'mo_chukouyouwen');
        _this.addPoint(new meta_1.MockField(gfrm_1.GroupFieldsRelationalMapping.KEY_MOCK_HuiLiuWenDu, 455, 2, '进口油温', '℃'), 'mo_jinkouyouwen');
        _this.addPoint(new meta_1.MockField('mo_huanrewendu', 457, 2, '换热温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_xitongwendu', 459, 2, '系统温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_nengliangshezhiwendu', 461, 2, '能量设置温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_zhengqiwendu', 463, 2, '蒸汽温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_shineiwendu', 1046, 2, '室内温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_1#dianliufankui', 1048, 2, '1#电流反馈', 'A'));
        _this.addPoint(new meta_1.MockField('mo_2#dianliufankui', 1050, 2, '2#电流反馈', 'A'));
        _this.addPoint(new meta_1.MockField('mo_3#dianliufankui', 1052, 2, '3#电流反馈', 'A'));
        _this.addPoint(new meta_1.MockField('mo_4#dianliufankui', 1054, 2, '4#电流反馈', 'A'));
        _this.addPoint(new meta_1.MockField('mo_5#dianliufankui', 1056, 2, '5#电流反馈', 'A'));
        _this.addPoint(new meta_1.MockField('mo_jiezhiwendu', 1058, 2, '介质温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_xiyuwendu', 1060, 2, '洗浴温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_huanjingwendu', 1062, 2, '环境温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_jiezhiyali', 1064, 2, '介质压力', 'KPa'));
        _this.addPoint(new meta_1.MockField('mo_a1', 1066, 2, '回路1进口温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_a2', 1068, 2, '回路2进口温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_a3', 1070, 2, '回路3进口温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_a4', 1072, 2, '回路4进口温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_a5', 1074, 2, '回路5进口温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_a6', 1076, 2, '空调系统温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_a7', 1078, 2, '地暖系统温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_a8', 1080, 2, '泳池系统温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_a9', 1082, 2, 'PH值', 'PH'));
        _this.addPoint(new meta_1.MockField('mo_a0', 1084, 2, '介质1温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_b1', 1086, 2, '介质2温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_b2', 1088, 2, '介质3温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_b3', 1090, 2, '介质4温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_b4', 1092, 2, '介质5温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_b5', 1094, 2, '介质6温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_b6', 1096, 2, '氮封压力', 'kPa'));
        _this.addPoint(new meta_1.MockField('mo_b7', 1098, 2, '熔盐槽温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_b8', 1100, 2, '采暖回水温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_b9', 1102, 2, '生活回水温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_b0', 1104, 2, '出口PH值', 'PH'));
        _this.addPoint(new meta_1.MockField('mo_c1', 1106, 2, '进口PH值', 'PH'));
        _this.addPoint(new meta_1.MockField('mo_c2', 1108, 2, '排烟温度1', '℃'));
        _this.addPoint(new meta_1.MockField('mo_c3', 1110, 2, '排烟温度2', '℃'));
        _this.addPoint(new meta_1.MockField('mo_c4', 1112, 2, '出口油压', 'MPa'));
        _this.addPoint(new meta_1.MockField('mo_c5', 1114, 2, '进口油压', 'MPa'));
        _this.addPoint(new meta_1.MockField('mo_c6', 1116, 2, '回水温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_c7', 1118, 2, '出口电导率', 'us/cm'));
        _this.addPoint(new meta_1.MockField('mo_c8', 1120, 2, '进口电导率', 'us/cm'));
        _this.addPoint(new meta_1.MockField('mo_c9', 1122, 2, '原水箱液位', 'mm'));
        _this.addPoint(new meta_1.MockField('mo_c0', 1124, 2, '纯水箱液位', 'mm'));
        _this.addPoint(new meta_1.MockField('mo_d1', 1126, 2, '减温水阀位反馈', '%'));
        _this.addPoint(new meta_1.MockField('mo_d2', 1128, 2, '炉水压力', 'MPa'));
        _this.addPoint(new meta_1.MockField('mo_shineiwendu', 1046, 2, '室内温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_1#dianliufankui', 1048, 2, '1#电流反馈', 'A'));
        _this.addPoint(new meta_1.MockField('mo_2#dianliufankui', 1050, 2, '2#电流反馈', 'A'));
        _this.addPoint(new meta_1.MockField('mo_3#dianliufankui', 1052, 2, '3#电流反馈', 'A'));
        _this.addPoint(new meta_1.MockField('mo_4#dianliufankui', 1054, 2, '4#电流反馈', 'A'));
        _this.addPoint(new meta_1.MockField('mo_5#dianliufankui', 1056, 2, '5#电流反馈', 'A'));
        _this.addPoint(new meta_1.MockField('mo_jiezhiwendu', 1058, 2, '介质温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_xiyuwendu', 1060, 2, '洗浴温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_huanjingwendu', 1062, 2, '环境温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_jiezhiyali', 1064, 2, '介质压力', 'KPa'));
        _this.addPoint(new meta_1.MockField('mo_shineiwendu', 1046, 2, '室内温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_1#dianliufankui', 1048, 2, '1#电流反馈', 'A'));
        _this.addPoint(new meta_1.MockField('mo_2#dianliufankui', 1050, 2, '2#电流反馈', 'A'));
        _this.addPoint(new meta_1.MockField('mo_3#dianliufankui', 1052, 2, '3#电流反馈', 'A'));
        _this.addPoint(new meta_1.MockField('mo_4#dianliufankui', 1054, 2, '4#电流反馈', 'A'));
        _this.addPoint(new meta_1.MockField('mo_5#dianliufankui', 1056, 2, '5#电流反馈', 'A'));
        _this.addPoint(new meta_1.MockField('mo_jiezhiwendu', 1058, 2, '介质温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_xiyuwendu', 1060, 2, '洗浴温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_huanjingwendu', 1062, 2, '环境温度', '℃'));
        _this.addPoint(new meta_1.MockField('mo_jiezhiyali', 1064, 2, '介质压力', 'KPa'));
        _this.addPoint(new meta_1.SettingField('se_paiyanwendu', 465, 2, '排烟温度', '℃', 0, Map_CTL_NJZJ_IP_Http.Commands_Key_Parameters_Setting, '0500', 50, 300));
        _this.addPoint(new meta_1.SettingField('se_baojingwendu', 467, 2, '报警温度', '℃', 0, Map_CTL_NJZJ_IP_Http.Commands_Key_Parameters_Setting, '0501', 0, 200));
        _this.addPoint(new meta_1.SettingField('se_tingluwendu', 469, 2, '停炉温度', '℃', 0, Map_CTL_NJZJ_IP_Http.Commands_Key_Parameters_Setting, '0502', 30, 200));
        _this.addPoint(new meta_1.SettingField('se_mubiaowendu', 471, 2, '目标温度', '℃', 0, Map_CTL_NJZJ_IP_Http.Commands_Key_Parameters_Setting, '0503', 30, 200));
        _this.addPoint(new meta_1.SettingField('se_qiluwendu', 473, 2, '启炉温度', '℃', 0, Map_CTL_NJZJ_IP_Http.Commands_Key_Parameters_Setting, '0504', 0, 200));
        _this.addPoint(new meta_1.SettingField('se_zhuanhuohuichawendu', 475, 2, '转火回差温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_qiluhuichawendu', 477, 2, '启炉回差温度', '℃', 0, Map_CTL_NJZJ_IP_Http.Commands_Key_Parameters_Setting, '0506', 1, 100));
        _this.addPoint(new meta_1.SettingField('se_kaibengwendu', 479, 2, '开泵温度', '℃', 0, Map_CTL_NJZJ_IP_Http.Commands_Key_Parameters_Setting, '0507', 0, 200));
        _this.addPoint(new meta_1.SettingField('se_guanbengwendu', 481, 2, '关泵温度', '℃', 0, Map_CTL_NJZJ_IP_Http.Commands_Key_Parameters_Setting, '0508', 0, 200));
        _this.addPoint(new meta_1.SettingField('se_baojingyali', 483, 2, '报警压力', 'MPa', 100));
        _this.addPoint(new meta_1.SettingField('se_tingluyali', 485, 2, '停炉压力', 'MPa', 100));
        _this.addPoint(new meta_1.SettingField('se_mubiaoyali', 487, 2, '目标压力', 'MPa', 100));
        _this.addPoint(new meta_1.SettingField('se_qiluyali', 489, 2, '启炉压力', 'MPa', 100));
        _this.addPoint(new meta_1.SettingField('se_zhuanhuohuichayali', 491, 2, '转火回差压力', 'MPa', 100));
        _this.addPoint(new meta_1.SettingField('se_qiluhuichayali', 493, 2, '启炉回差压力', 'MPa', 100));
        _this.addPoint(new meta_1.SettingField('se_qianyanshi', 495, 2, '前延时', 'S', 0, Map_CTL_NJZJ_IP_Http.Commands_Key_Parameters_Setting, '050F', 1, 60));
        _this.addPoint(new meta_1.SettingField('se_houyanshimiao', 497, 2, '后延时秒', 'S', 0, Map_CTL_NJZJ_IP_Http.Commands_Key_Parameters_Setting, '0510', 1, 60));
        _this.addPoint(new meta_1.SettingField('se_qianchuisao', 499, 2, '前吹扫', 'S'));
        _this.addPoint(new meta_1.SettingField('se_houchuisao', 501, 2, '后吹扫', 'S'));
        _this.addPoint(new meta_1.SettingField('se_lubibaojingwendu', 503, 2, '炉壁报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_lutangchukoubaojingwendu', 505, 2, '炉膛出口报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_baohuwendu', 507, 2, '保护温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_bentipaiyanwendubaojingzhi', 509, 2, '本体排烟温度报警值', '℃'));
        _this.addPoint(new meta_1.SettingField('se_jiarezushu', 511, 2, '加热组数', '组', 0, Map_CTL_NJZJ_IP_Http.Commands_Key_Parameters_Setting, '0517', 1, 100));
        _this.addPoint(new meta_1.SettingField('se_jianceyalishijian', 513, 2, '检测压力时间'));
        _this.addPoint(new meta_1.SettingField('se_houyanshifen', 515, 2, '后延时分', 'm'));
        _this.addPoint(new meta_1.SettingField('se_shedingwendu', 517, 2, '设定温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_mokuailutaishu', 519, 2, '模块炉台数'));
        _this.addPoint(new meta_1.SettingField('se_gufenghouyanshi', 521, 2, '鼓风后延时', 'S'));
        _this.addPoint(new meta_1.SettingField('se_yinfenghouyanshi', 523, 2, '引风后延时', 'S'));
        _this.addPoint(new meta_1.SettingField('se_shuixiangkaibengwendu', 525, 2, '水箱开泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_shuixiangguanbengwendu', 527, 2, '水箱关泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_lushuibaojingwendu', 529, 2, '炉水报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_buchangxishu', 531, 2, '补偿系数'));
        _this.addPoint(new meta_1.SettingField('se_cankaowendu', 533, 2, '参考温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_tingluzuidazhi', 535, 2, '停炉最大值', '℃'));
        _this.addPoint(new meta_1.SettingField('se_qiluzuixiaozhi', 537, 2, '启炉最小值', '℃'));
        _this.addPoint(new meta_1.SettingField('se_cankaohuicha', 539, 2, '参考回差', '℃'));
        _this.addPoint(new meta_1.SettingField('se_tingluwendu1', 541, 2, '停炉温度1', '℃'));
        _this.addPoint(new meta_1.SettingField('se_qiluwendu1', 543, 2, '启炉温度1', '℃'));
        _this.addPoint(new meta_1.SettingField('se_tingluwendu2', 545, 2, '停炉温度2', '℃'));
        _this.addPoint(new meta_1.SettingField('se_qiluwendu2', 547, 2, '启炉温度2', '℃'));
        _this.addPoint(new meta_1.SettingField('se_yusongliaoshijian', 549, 2, '预送料时间', 'S'));
        _this.addPoint(new meta_1.SettingField('se_dianhuoshijian', 551, 2, '点火时间', 'S'));
        _this.addPoint(new meta_1.SettingField('se_songliaoqidongshijian', 553, 2, '送料启动时间', 'S'));
        _this.addPoint(new meta_1.SettingField('se_songliaotingzhishijian', 555, 2, '送料停止时间', 'S'));
        _this.addPoint(new meta_1.SettingField('se_dianhuojiange', 557, 2, '点火间隔', 'm'));
        _this.addPoint(new meta_1.SettingField('se_dianhuochenggongwendu', 559, 2, '点火成功温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_lushuitingluwendu', 561, 2, '炉水停炉温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_lushuiqiluwendu', 563, 2, '炉水启炉温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_meishuibaojingwendu', 565, 2, '媒水报警温度', '℃', 0, Map_CTL_NJZJ_IP_Http.Commands_Key_Parameters_Setting, '0532', 50, 200));
        _this.addPoint(new meta_1.SettingField('se_meishuitingluwendu', 567, 2, '媒水停炉温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_meishuiqiluwendu', 569, 2, '媒水启炉温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_kaibengyali', 571, 2, '开泵压力', 'MPa', 100));
        _this.addPoint(new meta_1.SettingField('se_guanbengyali', 573, 2, '关泵压力', 'MPa', 100));
        _this.addPoint(new meta_1.SettingField('se_panguanbaojingwendu', 575, 2, '盘管报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_huilu1baojingwendu', 577, 2, '回路1报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_huilu1kaibengwendu', 579, 2, '回路1开泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_huilu1guanbengwendu', 581, 2, '回路1关泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_huilu2baojingwendu', 583, 2, '回路2报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_huilu2kaibengwendu', 585, 2, '回路2开泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_huilu2guanbengwendu', 587, 2, '回路2关泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_huilu3baojingwendu', 589, 2, '回路3报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_huilu3kaibengwendu', 591, 2, '回路3开泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_huilu3guanbengwendu', 593, 2, '回路3关泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_huilu4baojingwendu', 595, 2, '回路4报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_huilu4kaibengwendu', 597, 2, '回路4开泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_huilu4guanbengwendu', 599, 2, '回路4关泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_huilu5baojingwendu', 601, 2, '回路5报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_huilu5kaibengwendu', 603, 2, '回路5开泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_huilu5guanbengwendu', 605, 2, '回路5关泵温度', '℃'));
        //-------------------------------------------设置参数扩展----------------------------------------
        _this.addPoint(new meta_1.SettingField('se_touqieshijian_jiarezuyong_', 631, 2, '投切时间（加热组用）', 's', 0, Map_CTL_NJZJ_IP_Http.Commands_Key_Parameters_Setting, '0547', 1, 10));
        _this.addPoint(new meta_1.SettingField('se_diaojieshijian_jiarezuyong_', 633, 2, '调节时间（加热组用）', 'm', 0, Map_CTL_NJZJ_IP_Http.Commands_Key_Parameters_Setting, '0548', 1, 10));
        _this.addPoint(new meta_1.SettingField('se_chukouchaoyabaojing', 635, 2, '出口超压报警', 'MPa', 100));
        _this.addPoint(new meta_1.SettingField('se_jinkouchaoyabaojing', 637, 2, '进口超压报警', 'MPa', 100));
        _this.addPoint(new meta_1.SettingField('se_cainuanbaojingwendu', 639, 2, '采暖报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_cainuankaibengwendu', 641, 2, '采暖开泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_cainuanguanbengwendu', 643, 2, '采暖关泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_reshuibaojingwendu', 645, 2, '热水报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_reshuikaibengwendu', 647, 2, '热水开泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_reshuiguanbengwendu', 649, 2, '热水关泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_meishuimubiaowendu', 651, 2, '媒水目标温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_meishuiqiluhuicha', 653, 2, '媒水启炉回差', '℃'));
        _this.addPoint(new meta_1.SettingField('se_chukoudiyabaojing', 655, 2, '出口低压报警', '℃'));
        _this.addPoint(new meta_1.SettingField('se_jinchukouyachagao', 657, 2, '进出口压差高', '℃'));
        _this.addPoint(new meta_1.SettingField('se_jinchukouyachadi', 659, 2, '进出口压差低', '℃'));
        _this.addPoint(new meta_1.SettingField('se_jinkoudiyabaojing', 661, 2, '进口低压报警', '℃'));
        _this.addPoint(new meta_1.SettingField('se_jinkouchaowenbaojing', 663, 2, '进口超温报警', '℃'));
        _this.addPoint(new meta_1.SettingField('se_jinkoudiwenbaojing', 665, 2, '进口低温报警', '℃'));
        _this.addPoint(new meta_1.SettingField('se_chukoudiwenbaojing', 667, 2, '出口低温报警', '℃'));
        _this.addPoint(new meta_1.SettingField('se_pengzhangguanchaowen', 669, 2, '膨胀罐超温', '℃'));
        _this.addPoint(new meta_1.SettingField('se_mubiaoyewei', 671, 2, '目标液位', 'mm'));
        _this.addPoint(new meta_1.SettingField('se_kaibengyewei', 673, 2, '开泵液位', 'mm'));
        _this.addPoint(new meta_1.SettingField('se_guanbengyewei', 675, 2, '关泵液位', 'mm'));
        _this.addPoint(new meta_1.SettingField('se_kongbengmubiao', 677, 2, '控泵目标', '℃'));
        _this.addPoint(new meta_1.SettingField('se_lengningqianyanshi', 679, 2, '冷凝前延时', 's'));
        //----------------------------------------设置参数扩展-----------------------------------------
        _this.addPoint(new meta_1.SettingField('se_lengninghouyanshi', 1178, 2, '冷凝后延时', 's'));
        _this.addPoint(new meta_1.SettingField('se_xieyashangxian', 1180, 2, '泄压上限', 'MPa', 100));
        _this.addPoint(new meta_1.SettingField('se_xieyaxiaxian', 1182, 2, '泄压下限', 'MPa', 100));
        _this.addPoint(new meta_1.SettingField('se_jishuibaojingyali', 1184, 2, '给水报警压力', 'MPa', 100));
        _this.addPoint(new meta_1.SettingField('se_zhenkongbaojingyali', 1186, 2, '真空报警压力', 'KPa'));
        _this.addPoint(new meta_1.SettingField('se_zhenkongyalishangxian', 1188, 2, '真空压力上限', 'KPa'));
        _this.addPoint(new meta_1.SettingField('se_zhenkongyalixiaxian', 1190, 2, '真空压力下限', 'KPa'));
        _this.addPoint(new meta_1.SettingField('se_jinchukoumubiaoyacha', 1192, 2, '进出口目标压差', 'MPa', 100));
        _this.addPoint(new meta_1.SettingField('se_jienengqichuyanchaowen', 1194, 2, '节能器出烟超温', '℃'));
        _this.addPoint(new meta_1.SettingField('se_lengningqichuyanchaowen', 1196, 2, '冷凝器出烟超温', '℃'));
        _this.addPoint(new meta_1.SettingField('se_jinshuitingluwendu', 1198, 2, '进水停炉温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_youwenbaohuwendu', 1200, 2, '油温保护温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_youwenshangxianwendu', 1202, 2, '油温上限温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_youwenzhongxianwendu', 1204, 2, '油温中限温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_gaowenbaohuwendu', 1206, 2, '高温保护温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_wenchabaohuwendu', 1208, 2, '温差保护温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_jinkoutingluwendu', 1210, 2, '进口停炉温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_jinkoumubiaowendu', 1212, 2, '进口目标温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_jinkouqiluhuicha', 1214, 2, '进口启炉回差', '℃'));
        _this.addPoint(new meta_1.SettingField('se_youwenxiaxianwendu', 1216, 2, '油温下限温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_huanrekaibengwendu', 1218, 2, '换热开泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_huanreguanbengwendu', 1220, 2, '换热关泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_xitongkaibengwendu', 1222, 2, '系统开泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_xitongguanbengwendu', 1224, 2, '系统关泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_a0', 1226, 2, '烟道蝶阀行程', 's'));
        _this.addPoint(new meta_1.SettingField('se_a1', 1228, 2, '烟道蝶阀延时', 's'));
        _this.addPoint(new meta_1.SettingField('se_a2', 1230, 2, '温差上限温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_a3', 1232, 2, '温差下限温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_a4', 1234, 2, '出水停炉温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_a5', 1236, 2, '蒸汽报警', '℃'));
        _this.addPoint(new meta_1.SettingField('se_a6', 1238, 2, '蒸汽停炉', '℃'));
        _this.addPoint(new meta_1.SettingField('se_a7', 1240, 2, '蒸汽目标', '℃'));
        _this.addPoint(new meta_1.SettingField('se_a8', 1242, 2, '蒸汽回差', '℃'));
        _this.addPoint(new meta_1.SettingField('se_a9', 1244, 2, '低报警液位', 'mm'));
        _this.addPoint(new meta_1.SettingField('se_b0', 1246, 2, '高报警液位', 'mm'));
        _this.addPoint(new meta_1.SettingField('se_b1', 1248, 2, '采暖停炉温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_b2', 1250, 2, '采暖启炉温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_b3', 1252, 2, '1#报警电流', 'A'));
        _this.addPoint(new meta_1.SettingField('se_b4', 1254, 2, '2#报警电流', 'A'));
        _this.addPoint(new meta_1.SettingField('se_b5', 1256, 2, '3#报警电流', 'A'));
        _this.addPoint(new meta_1.SettingField('se_b6', 1258, 2, '4#报警电流', 'A'));
        _this.addPoint(new meta_1.SettingField('se_b7', 1260, 2, '5#报警电流', 'A'));
        _this.addPoint(new meta_1.SettingField('se_b8', 1262, 2, '介质超温报警', '℃'));
        _this.addPoint(new meta_1.SettingField('se_b9', 1264, 2, '介质超温恢复', '℃'));
        _this.addPoint(new meta_1.SettingField('se_c0', 1266, 2, '介质低温报警', '℃'));
        _this.addPoint(new meta_1.SettingField('se_c1', 1268, 2, '介质低温恢复', '℃'));
        _this.addPoint(new meta_1.SettingField('se_c2', 1270, 2, '循环惯性时间', 's'));
        _this.addPoint(new meta_1.SettingField('se_c3', 1272, 2, '洗浴报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_c4', 1274, 2, '洗浴开泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_c5', 1276, 2, '洗浴关泵温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_c6', 1278, 2, '介质超压报警', 'kPa'));
        _this.addPoint(new meta_1.SettingField('se_c7', 1280, 2, '介质超压恢复', 'kPa'));
        _this.addPoint(new meta_1.SettingField('se_c8', 1282, 2, '循环报警流量1', 'm³/h', 10));
        _this.addPoint(new meta_1.SettingField('se_c9', 1284, 2, '空调报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_d0', 1286, 2, '地暖报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_d1', 1288, 2, '泳池报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_d2', 1290, 2, '循环报警流量2', 'm³/h'));
        _this.addPoint(new meta_1.SettingField('se_d3', 1292, 2, '启动间隔时间', 's'));
        _this.addPoint(new meta_1.SettingField('se_d4', 1294, 2, '停止间隔时间', 's'));
        _this.addPoint(new meta_1.SettingField('se_d5', 1296, 2, 'PH值上限', 'PH', 10));
        _this.addPoint(new meta_1.SettingField('se_d6', 1298, 2, 'PH值下限', 'PH', 10));
        _this.addPoint(new meta_1.SettingField('se_d7', 1300, 2, '报警温度1', '℃'));
        _this.addPoint(new meta_1.SettingField('se_d8', 1302, 2, '停炉温度1', '℃'));
        _this.addPoint(new meta_1.SettingField('se_d9', 1304, 2, '启炉温度1', '℃'));
        _this.addPoint(new meta_1.SettingField('se_e0', 1306, 2, '报警温度2', '℃'));
        _this.addPoint(new meta_1.SettingField('se_e1', 1308, 2, '停炉温度2', '℃'));
        _this.addPoint(new meta_1.SettingField('se_e2', 1310, 2, '启炉温度2', '℃'));
        _this.addPoint(new meta_1.SettingField('se_e3', 1312, 2, '报警温度3', '℃'));
        _this.addPoint(new meta_1.SettingField('se_e4', 1314, 2, '停炉温度3', '℃'));
        _this.addPoint(new meta_1.SettingField('se_e5', 1316, 2, '启炉温度3', '℃'));
        _this.addPoint(new meta_1.SettingField('se_e6', 1318, 2, '节能器进烟超温', '℃'));
        _this.addPoint(new meta_1.SettingField('se_e7', 1320, 2, '目标流量1', 'm³/h', 10));
        _this.addPoint(new meta_1.SettingField('se_e8', 1322, 2, '目标流量2', 'm³/h'));
        _this.addPoint(new meta_1.SettingField('se_e9', 1324, 2, '引鼓启动间隔', 's'));
        _this.addPoint(new meta_1.SettingField('se_f0', 1326, 2, '鼓引停止间隔', 's'));
        _this.addPoint(new meta_1.SettingField('se_f1', 1328, 2, '水箱报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_f2', 1330, 2, '采暖目标温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_f3', 1332, 2, '采暖启炉回差', '℃'));
        _this.addPoint(new meta_1.SettingField('se_f4', 1334, 2, '热水停炉温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_f5', 1336, 2, '热水目标温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_f6', 1338, 2, '热水启炉回差', '℃'));
        _this.addPoint(new meta_1.SettingField('se_f7', 1340, 2, '冲洗周期', 'm'));
        _this.addPoint(new meta_1.SettingField('se_f8', 1342, 2, '冲洗时间', 's'));
        _this.addPoint(new meta_1.SettingField('se_f9', 1344, 2, '出水报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_g0', 1346, 2, '进水报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_g1', 1348, 2, '上限流量2', 'm³/h'));
        _this.addPoint(new meta_1.SettingField('se_g2', 1350, 2, '下限流量2', 'm³/h'));
        _this.addPoint(new meta_1.SettingField('se_g3', 1352, 2, '点火检测时间', 's'));
        _this.addPoint(new meta_1.SettingField('se_g4', 1354, 2, '排污周期', 'm'));
        _this.addPoint(new meta_1.SettingField('se_g5', 1356, 2, '排污时间', 's'));
        _this.addPoint(new meta_1.SettingField('se_g6', 1358, 2, '充氮开阀压力', 'kPa'));
        _this.addPoint(new meta_1.SettingField('se_g7', 1360, 2, '充氮关阀压力', 'kPa'));
        _this.addPoint(new meta_1.SettingField('se_g8', 1362, 2, '泄氮开阀压力', 'kPa'));
        _this.addPoint(new meta_1.SettingField('se_g9', 1364, 2, '泄氮关阀压力', 'kPa'));
        _this.addPoint(new meta_1.SettingField('se_h0', 1366, 2, '炉膛超温报警', '℃'));
        _this.addPoint(new meta_1.SettingField('se_h1', 1368, 2, '开阀液位', 'mm'));
        _this.addPoint(new meta_1.SettingField('se_h2', 1370, 2, '关阀液位', 'mm'));
        _this.addPoint(new meta_1.SettingField('se_h3', 1372, 2, '炉膛超压报警', 'Pa'));
        _this.addPoint(new meta_1.SettingField('se_h4', 1374, 2, '切换周期', 'h'));
        _this.addPoint(new meta_1.SettingField('se_h5', 1376, 2, 'PH值回差', 'PH', 10));
        _this.addPoint(new meta_1.SettingField('se_h6', 1378, 2, '抽真空温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_h7', 1380, 2, '燃气超压报警', 'kPa'));
        _this.addPoint(new meta_1.SettingField('se_h8', 1382, 2, '油压保护压力', 'MPa', 100));
        _this.addPoint(new meta_1.SettingField('se_h9', 1384, 2, '冷凝器出水超温', '℃'));
        _this.addPoint(new meta_1.SettingField('se_i0', 1386, 2, '引风高速', '%'));
        _this.addPoint(new meta_1.SettingField('se_i1', 1388, 2, '引风低速', '%'));
        _this.addPoint(new meta_1.SettingField('se_i2', 1390, 2, '前延时', 'm'));
        _this.addPoint(new meta_1.SettingField('se_i3', 1392, 2, '储罐报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_i4', 1394, 2, '进口油压高报警', 'MPa', 100));
        _this.addPoint(new meta_1.SettingField('se_i5', 1396, 2, '进口油压低报警', 'MPa', 100));
        _this.addPoint(new meta_1.SettingField('se_i6', 1398, 2, '燃气低压报警', 'kPa'));
        _this.addPoint(new meta_1.SettingField('se_i7', 1400, 2, '热水启炉温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_i8', 1402, 2, '炉膛压力', 'Pa'));
        _this.addPoint(new meta_1.SettingField('se_i9', 1404, 2, '热风报警温度', '℃'));
        _this.addPoint(new meta_1.SettingField('se_j0', 1406, 2, '鼓风反馈低报警', '%'));
        _this.addPoint(new meta_1.SettingField('se_j1', 1408, 2, '送料启动时间2', 's', 0, Map_CTL_NJZJ_IP_Http.Commands_Key_Parameters_Setting, '0053', 0, 600));
        _this.addPoint(new meta_1.SettingField('se_j2', 1410, 2, '送料停止时间2', 's', 0, Map_CTL_NJZJ_IP_Http.Commands_Key_Parameters_Setting, '0054', 0, 600));
        _this.addPoint(new meta_1.SettingField('se_j3', 1412, 2, '送料启动时间3', 's', 0, Map_CTL_NJZJ_IP_Http.Commands_Key_Parameters_Setting, '0055', 0, 600));
        _this.addPoint(new meta_1.SettingField('se_j4', 1414, 2, '送料停止时间3', 's', 0, Map_CTL_NJZJ_IP_Http.Commands_Key_Parameters_Setting, '0056', 0, 600));
        // this.addPoint(new SettingField('se_d0', 1326, 2, '', '℃'))
        // this.addPoint(new SettingField('se_d1', 1328, 2, '', '℃'))
        // this.addPoint(new SettingField('se_d2', 1330, 2, '', '℃'))
        // this.addPoint(new SettingField('se_d3', 1332, 2, '', '℃'))
        // this.addPoint(new SettingField('se_d4', 1334, 2, '', '℃'))
        // this.addPoint(new SettingField('se_d5', 1336, 2, '', '℃'))
        // this.addPoint(new SettingField('se_d6', 1338, 2, '', '℃'))
        // this.addPoint(new SettingField('se_d7', 1340, 2, '', '℃'))
        // this.addPoint(new SettingField('se_d8', 1342, 2, '', '℃'))
        // this.addPoint(new SettingField('se_d9', 1344, 2, '', '℃'))
        //启停时间
        _this.addPoint(new meta_1.StartStopField('st_qidongshijian1', 607, 2, '启动时间1'));
        _this.addPoint(new meta_1.StartStopField('st_tingzhishijian1', 609, 2, '停止时间1'));
        _this.addPoint(new meta_1.StartStopField('st_qidongshijian2', 611, 2, '启动时间2'));
        _this.addPoint(new meta_1.StartStopField('st_tingzhishijian2', 613, 2, '停止时间2'));
        _this.addPoint(new meta_1.StartStopField('st_qidongshijian3', 615, 2, '启动时间3'));
        _this.addPoint(new meta_1.StartStopField('st_tingzhishijian3', 617, 2, '停止时间3'));
        _this.addPoint(new meta_1.StartStopField('st_qidongshijian4', 619, 2, '启动时间4'));
        _this.addPoint(new meta_1.StartStopField('st_tingzhishijian4', 621, 2, '停止时间4'));
        _this.addPoint(new meta_1.StartStopField('st_qidongshijian5', 623, 2, '启动时间5'));
        _this.addPoint(new meta_1.StartStopField('st_tingzhishijian5', 625, 2, '停止时间5'));
        _this.addPoint(new meta_1.StartStopField('st_qidongshijian6', 627, 2, '启动时间6'));
        _this.addPoint(new meta_1.StartStopField('st_tingzhishijian6', 629, 2, '停止时间6'));
        _this.addPoint(new meta_1.RanShaoQiField('de_ranshaoqi', 681, 2, '燃烧器', Map_CTL_NJZJ_IP_Http.coms_ranshaoqi_status));
        //this.addPoint(new DeviceField('de_jiarezu', 683, 2, '加热组', Map_CTL_NJZJ_IP_Http.coms_device))
        _this.addPoint(new meta_1.JieReZuField('de_jiarezu', 683, 2, '加热组', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_bushui_beng', 685, 2, '补水泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_jishui_beng', 687, 2, '给水泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_buyou_beng', 689, 2, '补油泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_xunhuan_beng', 691, 2, '循环泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_lengning_beng', 693, 2, '冷凝泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_reshui_beng', 695, 2, '热水泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_zhenkong_beng', 697, 2, '真空泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_ecixunhuan_beng', 699, 2, '二次循环泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_yinfengji_fan', 701, 2, '引风机', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_gufengji_fan', 703, 2, '鼓风机', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField(CTL_NJZJ_2.IP.KEY_POINT_DEVICE_LUPAI, 705, 2, '炉排', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_chuzhaji_fan', 707, 2, '出渣机', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_ecigufengji_fan', 709, 2, '二次鼓风机', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_dianhuoqi', 711, 2, '点火器', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_shangmeiji', 713, 2, '上煤机', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField(CTL_NJZJ_2.IP.KEY_POINT_DEVICE_SONGLIAO, 715, 2, '送料机', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_jiayao_beng', 717, 2, '加药泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_paiwufa', 719, 2, '排污阀', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_huilu1xunhuan_beng', 721, 2, '回路1循环泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_huilu2xunhuan_beng', 723, 2, '回路2循环泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_huilu3xunhuan_beng', 725, 2, '回路3循环泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_huilu4xunhuan_beng', 727, 2, '回路4循环泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_huilu5xunhuan_beng', 729, 2, '回路5循环泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_cainuanxunhuan_beng', 731, 2, '采暖循环泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_reshuixunhuan_beng', 733, 2, '热水循环泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_paiqifa', 735, 2, '排汽阀', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_xieyafa', 737, 2, '泄压阀', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_zhenkongfa', 739, 2, '真空阀', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_pangtongfa', 741, 2, '旁通阀', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_churexunhuan_beng', 743, 2, '储热循环泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_huanrexunhuan_beng', 745, 2, '换热循环泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_xitongxunhuan_beng', 747, 2, '系统循环泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_churebushui_beng', 749, 2, '储热补水泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_yandaodiefa', 751, 2, '烟道蝶阀', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_huishui_beng', 753, 2, '回水泵', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField('de_santongfa', 755, 2, '三通阀', Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_xiyuxunhuanbeng", 757, 2, "洗浴循环泵", Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_reshuidiaojiefa", 759, 2, "热水调节阀", Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_jienengbeng", 761, 2, "节能泵", Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_kongdiaoxunhuanbeng", 763, 2, "空调循环泵", Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_dinuanxunhuanbeng", 765, 2, "地暖循环泵", Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_yongchixunhuanbeng", 767, 2, "泳池循环泵", Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_chuchenqi", 769, 2, "除尘器", Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_yuanshuibeng", 771, 2, "原水泵", Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_gaoyabeng", 773, 2, "高压泵", Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_jinshuifa", 775, 2, "进水阀", Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_chongxifa", 777, 2, "冲洗阀", Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_jishuibeng1", 779, 2, "给水泵1", Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_jishuibeng2", 781, 2, "给水泵2", Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_chongdanqifa", 783, 2, "充氮气阀", Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_xiedanqifa", 785, 2, "泄氮气阀", Map_CTL_NJZJ_IP_Http.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_jiarexitongfa", 787, 2, "加热系统阀", Map_CTL_NJZJ_IP_Http.coms_device));
        return _this;
        // this.addPoint(new DeviceField("de_paifangfa", 789, 2,  "排放阀",Map_CTL_NJZJ_IP_Http.coms_device));
        // this.addPoint(new DeviceField("de_boliaoji", 791, 2,  "拨料机",Map_CTL_NJZJ_IP_Http.coms_device));
        // this.addPoint(new DeviceField( "de_PHdiaojiebeng", 793, 2,  "PH调节泵",Map_CTL_NJZJ_IP_Http.coms_device));
        // this.addPoint(new DeviceField("de_diancifa1", 795, 2,  "电磁阀1",Map_CTL_NJZJ_IP_Http.coms_device));
        // this.addPoint(new DeviceField("de_diancifa2", 797, 2,  "电磁阀2",Map_CTL_NJZJ_IP_Http.coms_device));
        // this.addPoint(new DeviceField("de_bushuibeng1", 801, 2,  "补水泵1",Map_CTL_NJZJ_IP_Http.coms_device));
        // this.addPoint(new DeviceField("de_bushuibeng2", 803, 2,  "补水泵2",Map_CTL_NJZJ_IP_Http.coms_device));
        // this.addPoint(new DeviceField("de_jianwenshuifa", 805, 2,  "减温水阀",Map_CTL_NJZJ_IP_Http.coms_device));
        // this.addPoint(new DeviceField("de_V1fa", 807, 2,  "V1阀",Map_CTL_NJZJ_IP_Http.coms_device));
        // this.addPoint(new DeviceField("de_V2fa", 809, 2,  "V2阀",Map_CTL_NJZJ_IP_Http.coms_device));
    }
    Map_CTL_NJZJ_IP_Http.Commands_Key_Parameters_Setting = '参数设置';
    Map_CTL_NJZJ_IP_Http.Commands_Key_System_Ctl = '系统控制';
    return Map_CTL_NJZJ_IP_Http;
}(CTL_NJZJ_1.Map_CTL_NJZJ));
exports.Map_CTL_NJZJ_IP_Http = Map_CTL_NJZJ_IP_Http;
