"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
var CTL_NJZJ_1 = require("./CTL_NJZJ");
var meta_1 = require("../../../../meta/NJZJ/meta");
var meta_2 = require("../../../../meta/NJZJ/485/meta");
var CTL_NJZJ_IP_485_1749_1 = require("./CTL_NJZJ_IP_485_1749");
var Map_CTL_NJZJ_IP_485_2173 = /** @class */ (function (_super) {
    __extends(Map_CTL_NJZJ_IP_485_2173, _super);
    function Map_CTL_NJZJ_IP_485_2173() {
        var _this = _super.call(this) || this;
        _this.addPoint(new meta_1.SettingField('se_jiarezushu', 1114, 2, '加热组数', '组', 0, CTL_NJZJ_IP_485_1749_1.Map_CTL_NJZJ_IP_485_1749.Commands_Key_Parameters_Setting, '0517', 1, 15));
        //
        _this.addPoint(new meta_2.BaseInfoField("ba_qibao1shuiweizhuangtai", 63, 2, "汽包1水位状态", '', CTL_NJZJ_IP_485_1749_1.Map_CTL_NJZJ_IP_485_1749.coms_level));
        _this.addPoint(new meta_2.BaseInfoField("ba_qibao2shuiweizhuangtai", 65, 2, "汽包2水位状态", '', CTL_NJZJ_IP_485_1749_1.Map_CTL_NJZJ_IP_485_1749.coms_level));
        _this.addPoint(new meta_2.ExceptionField("ex_kongdiaoxitongwendugaobaojing", 353, 2, "空调系统温度高报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_dinuanxitongwendugaobaojing", 355, 2, "地暖系统温度高报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_yongchixitongwendugaobaojing", 357, 2, "泳池系统温度高报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_fengyagaobaojing", 359, 2, "风压高报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_fengyadibaojing", 361, 2, "风压低报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_shuixiangshuiweixinhaoluojicuobaojing", 363, 2, "水箱水位信号逻辑错报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_PHzhigaobaojing", 365, 2, "PH值高报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_PHzhidibaojing", 367, 2, "PH值低报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_chaowenbaojing1", 369, 2, "超温报警1"));
        _this.addPoint(new meta_2.ExceptionField("ex_chaowenbaojing2", 371, 2, "超温报警2"));
        _this.addPoint(new meta_2.ExceptionField("ex_chaowenbaojing3", 373, 2, "超温报警3"));
        _this.addPoint(new meta_2.ExceptionField("ex_jienengqijinkouyanwengaobaojing", 375, 2, "节能器进口烟温高报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_shuixiangqueshuibaojing", 377, 2, "水箱缺水报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_1#morukuozhanmokuaitongxunyichang", 379, 2, "1#模入扩展模块通讯异常"));
        _this.addPoint(new meta_2.ExceptionField("ex_huilu1jinkouwenduchuanganqiguzhang", 786, 2, "回路1进口温度传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_huilu2jinkouwenduchuanganqiguzhang", 788, 2, "回路2进口温度传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_huilu3jinkouwenduchuanganqiguzhang", 790, 2, "回路3进口温度传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_huilu4jinkouwenduchuanganqiguzhang", 792, 2, "回路4进口温度传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_huilu5jinkouwenduchuanganqiguzhang", 794, 2, "回路5进口温度传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_kongdiaoxitongwenduchuanganqiguzhang", 796, 2, "空调系统温度传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_dinuanxitongwenduchuanganqiguzhang", 798, 2, "地暖系统温度传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_yongchixitongwenduchuanganqiguzhang", 800, 2, "泳池系统温度传感器故障"));
        _this.addPoint(new meta_1.MockField("mo_huilu1jinkouwendu", 1031, 2, "回路1进口温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_huilu2jinkouwendu", 1033, 2, "回路2进口温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_huilu3jinkouwendu", 1035, 2, "回路3进口温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_huilu4jinkouwendu", 1037, 2, "回路4进口温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_huilu5jinkouwendu", 1039, 2, "回路5进口温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_kongdiaoxitongwendu", 1041, 2, "空调系统温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_dinuanxitongwendu", 1043, 2, "地暖系统温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_yongchixitongwendu", 1045, 2, "泳池系统温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_PHzhi", 1047, 2, "PH值", "PH"));
        _this.addPoint(new meta_1.MockField("mo_jiezhi1wendu", 1049, 2, "介质1温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_jiezhi2wendu", 1051, 2, "介质2温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_jiezhi3wendu", 1053, 2, "介质3温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_jiezhi4wendu", 1055, 2, "介质4温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_jiezhi5wendu", 1057, 2, "介质5温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_jiezhi6wendu", 1059, 2, "介质6温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_danfengyali", 1061, 2, "氮封压力", "℃"));
        _this.addPoint(new meta_1.SettingField("se_1#baojingdianliu", 1323, 2, "1#报警电流", "A"));
        _this.addPoint(new meta_1.SettingField("se_2#baojingdianliu", 1325, 2, "2#报警电流", "A"));
        _this.addPoint(new meta_1.SettingField("se_3#baojingdianliu", 1327, 2, "3#报警电流", "A"));
        _this.addPoint(new meta_1.SettingField("se_4#baojingdianliu", 1329, 2, "4#报警电流", "A"));
        _this.addPoint(new meta_1.SettingField("se_5#baojingdianliu", 1331, 2, "5#报警电流", "A"));
        _this.addPoint(new meta_1.SettingField("se_jiezhichaowenbaojing", 1333, 2, "介质超温报警", "℃"));
        _this.addPoint(new meta_1.SettingField("se_jiezhichaowenhuifu", 1335, 2, "介质超温恢复", "℃"));
        _this.addPoint(new meta_1.SettingField("se_jiezhidiwenbaojing", 1337, 2, "介质低温报警", "℃"));
        _this.addPoint(new meta_1.SettingField("se_jiezhidiwenhuifu", 1339, 2, "介质低温恢复", "℃"));
        _this.addPoint(new meta_1.SettingField("se_xunhuanguanxingshijian", 1341, 2, "循环惯性时间", "S"));
        _this.addPoint(new meta_1.SettingField("se_xiyubaojingwendu", 1343, 2, "洗浴报警温度", "S"));
        _this.addPoint(new meta_1.SettingField("se_xiyukaibengwendu", 1345, 2, "洗浴开泵温度", "S"));
        _this.addPoint(new meta_1.SettingField("se_xiyuguanbengwendu", 1347, 2, "洗浴关泵温度", "S"));
        _this.addPoint(new meta_1.SettingField("se_jiezhichaoyabaojing", 1349, 2, "介质超压报警", "kPa"));
        _this.addPoint(new meta_1.SettingField("se_jiezhichaoyahuifu", 1351, 2, "介质超压恢复", "kPa"));
        _this.addPoint(new meta_1.SettingField("se_xunhuanbaojingliuliang1", 1353, 2, "循环报警流量1", "m3/h", 10));
        _this.addPoint(new meta_1.SettingField("se_kongdiaobaojingwendu", 1355, 2, "空调报警温度", "℃"));
        _this.addPoint(new meta_1.SettingField("se_dinuanbaojingwendu", 1357, 2, "地暖报警温度", "℃"));
        _this.addPoint(new meta_1.SettingField("se_yongchibaojingwendu", 1359, 2, "泳池报警温度", "℃"));
        _this.addPoint(new meta_1.SettingField("se_xunhuanbaojingliuliang2", 1361, 2, "循环报警流量2", "m3/H"));
        _this.addPoint(new meta_1.SettingField("se_qidongjiangeshijian", 1363, 2, "启动间隔时间", "S"));
        _this.addPoint(new meta_1.SettingField("se_tingzhijiangeshijian", 1365, 2, "停止间隔时间", "S"));
        _this.addPoint(new meta_1.SettingField("se_PHzhishangxian", 1367, 2, "PH值上限", "PH", 10));
        _this.addPoint(new meta_1.SettingField("se_PHzhixiaxian", 1369, 2, "PH值下限", "PH", 10));
        _this.addPoint(new meta_1.SettingField("se_baojingwendu1", 1371, 2, "报警温度1", "℃"));
        _this.addPoint(new meta_1.SettingField("se_tingluwendu1", 1373, 2, "停炉温度1", "℃"));
        _this.addPoint(new meta_1.SettingField("se_qiluwendu1", 1375, 2, "启炉温度1", "℃"));
        _this.addPoint(new meta_1.SettingField("se_baojingwendu2", 1377, 2, "报警温度2", "℃"));
        _this.addPoint(new meta_1.SettingField("se_tingluwendu2", 1379, 2, "停炉温度2", "℃"));
        _this.addPoint(new meta_1.SettingField("se_qiluwendu2", 1381, 2, "启炉温度2", "℃"));
        _this.addPoint(new meta_1.SettingField("se_baojingwendu3", 1383, 2, "报警温度3", "℃"));
        _this.addPoint(new meta_1.SettingField("se_tingluwendu3", 1385, 2, "停炉温度3", "℃"));
        _this.addPoint(new meta_1.SettingField("se_qiluwendu3", 1387, 2, "启炉温度3", "℃"));
        _this.addPoint(new meta_1.SettingField("se_jienengqijinyanchaowen", 1389, 2, "节能器进烟超温", "℃"));
        _this.addPoint(new meta_1.SettingField("se_mubiaoliuliang1", 1391, 2, "目标流量1", "m3/h", 10));
        _this.addPoint(new meta_1.SettingField("se_mubiaoliuliang2", 1393, 2, "目标流量2", "m3/H"));
        _this.addPoint(new meta_1.SettingField("se_yinguqidongjiange", 1395, 2, "引鼓启动间隔", "S"));
        _this.addPoint(new meta_1.SettingField("se_guyintingzhijiange", 1397, 2, "鼓引停止间隔", "S"));
        _this.addPoint(new meta_1.SettingField("mo_shuixiangbaojingwendu", 1399, 2, "水箱报警温度", "℃"));
        _this.addPoint(new meta_1.SettingField("se_cainuanmubiaowendu", 1401, 2, "采暖目标温度", "℃"));
        _this.addPoint(new meta_1.SettingField("se_cainuanqiluhuicha", 1403, 2, "采暖启炉回差", "℃"));
        _this.addPoint(new meta_1.SettingField("se_reshuitingluwendu", 1405, 2, "热水停炉温度", "℃"));
        _this.addPoint(new meta_1.SettingField("se_reshuimubiaowendu", 1407, 2, "热水目标温度", "℃"));
        _this.addPoint(new meta_1.SettingField("se_reshuiqiluhuicha", 1409, 2, "热水启炉回差", "℃"));
        _this.addPoint(new meta_1.SettingField("se_chongxizhouqi", 1411, 2, "冲洗周期", "min"));
        _this.addPoint(new meta_1.SettingField("se_chongxishijian", 1413, 2, "冲洗时间", "S"));
        _this.addPoint(new meta_1.SettingField("se_chushuibaojingwendu", 1415, 2, "出水报警温度", "℃"));
        _this.addPoint(new meta_1.SettingField("se_jinshuibaojingwendu", 1417, 2, "进水报警温度", "℃"));
        _this.addPoint(new meta_1.SettingField("se_shangxianliuliang2", 1419, 2, "上限流量2", "m3/H"));
        _this.addPoint(new meta_1.SettingField("se_xiaxianliuliang2", 1421, 2, "下限流量2", "m3/H"));
        _this.addPoint(new meta_1.SettingField("se_dianhuojianceshijian", 1423, 2, "点火检测时间", "S"));
        _this.addPoint(new meta_1.SettingField("se_paiwuzhouqi", 1425, 2, "排污周期", "min"));
        _this.addPoint(new meta_1.SettingField("se_paiwushijian", 1427, 2, "排污时间", "S"));
        _this.addPoint(new meta_1.SettingField("se_chongdankaifayali", 1429, 2, "充氮开阀压力", "kPa"));
        _this.addPoint(new meta_1.SettingField("se_chongdanguanfayali", 1431, 2, "充氮关阀压力", "kPa"));
        _this.addPoint(new meta_1.SettingField("se_xiedankaifayali", 1433, 2, "泄氮开阀压力", "kPa"));
        _this.addPoint(new meta_1.SettingField("se_xiedanguanfayali", 1435, 2, "泄氮关阀压力", "kPa"));
        _this.addPoint(new meta_1.SettingField("se_lutangchaowenbaojing", 1437, 2, "炉膛超温报警", "℃"));
        _this.addPoint(new meta_1.SettingField("se_kaifayewei", 1439, 2, "开阀液位", "mm"));
        _this.addPoint(new meta_1.SettingField("se_guanfayewei", 1441, 2, "关阀液位", "mm"));
        _this.addPoint(new meta_1.SettingField("se_lutangchaoyabaojing", 1443, 2, "炉膛超压报警", "Pa"));
        _this.addPoint(new meta_1.SettingField("se_qiehuanzhouqi", 1445, 2, "切换周期", "h"));
        _this.addPoint(new meta_1.SettingField("se_PHzhihuicha", 1447, 2, "PH值回差", "PH", 10));
        _this.addPoint(new meta_1.SettingField("se_chouzhenkongwendu", 1449, 2, "抽真空温度", "℃"));
        _this.addPoint(new meta_1.SettingField("se_ranqichaoyabaojing", 1451, 2, "燃气超压报警", "kPa"));
        _this.addPoint(new meta_1.SettingField("se_youyabaohuyali", 1453, 2, "油压保护压力", "MPa", 100));
        _this.addPoint(new meta_1.SettingField("se_lengningqichushuichaowen", 1455, 2, "冷凝器出水超温", "℃"));
        _this.addPoint(new meta_1.SettingField("se_yinfenggaosu", 1457, 2, "引风高速", "%"));
        _this.addPoint(new meta_1.SettingField("se_yinfengdisu", 1459, 2, "引风低速", "%"));
        _this.addPoint(new meta_1.SettingField("se_qianyanshi", 1461, 2, "前延时", "分钟"));
        _this.addPoint(new meta_1.SettingField("se_chuguanbaojingwendu", 1463, 2, "储罐报警温度", "℃"));
        _this.addPoint(new meta_1.SettingField("se_jinkouyouyagaobaojing", 1465, 2, "进口油压高报警", "MPa", 100));
        _this.addPoint(new meta_1.SettingField("se_jinkouyouyadibaojing", 1467, 2, "进口油压低报警", "MPa", 100));
        _this.addPoint(new meta_1.SettingField("se_ranqidiyabaojing", 1469, 2, "燃气低压报警", "kPa"));
        _this.addPoint(new meta_1.SettingField("se_reshuiqiluwendu", 1471, 2, "热水启炉温度", "℃"));
        _this.addPoint(new meta_1.SettingField("se_lutangyali", 1473, 2, "炉膛压力", "Pa"));
        _this.addPoint(new meta_1.SettingField("se_refengbaojingwendu", 1475, 2, "热风报警温度", "℃"));
        _this.addPoint(new meta_1.SettingField("se_gufengfankuidibaojing", 1477, 2, "鼓风反馈低报警", "%"));
        _this.addPoint(new meta_1.SettingField("se_songliaoqidongshijian2", 1479, 2, "送料启动时间2", "秒"));
        _this.addPoint(new meta_1.SettingField("se_songliaotingzhishijian2", 1481, 2, "送料停止时间2", "秒"));
        _this.addPoint(new meta_1.SettingField("se_songliaoqidongshijian3", 1483, 2, "送料启动时间3", "秒"));
        _this.addPoint(new meta_1.SettingField("se_songliaotingzhishijian3", 1485, 2, "送料停止时间3", "秒"));
        _this.addPoint(new meta_1.DeviceField("de_xiyuxunhuanbeng", 1663, 2, "洗浴循环泵", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_reshuidiaojiefa", 1665, 2, "热水调节阀", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_jienengbeng", 1667, 2, "节能泵", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_kongdiaoxunhuanbeng", 1669, 2, "空调循环泵", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_dinuanxunhuanbeng", 1671, 2, "地暖循环泵", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_yongchixunhuanbeng", 1673, 2, "泳池循环泵", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_chuchenqi", 1675, 2, "除尘器", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_yuanshuibeng", 1677, 2, "原水泵", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_gaoyabeng", 1679, 2, "高压泵", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_jinshuifa", 1681, 2, "进水阀", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_chongxifa", 1683, 2, "冲洗阀", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_jishuibeng1", 1685, 2, "给水泵1", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_jishuibeng2", 1687, 2, "给水泵2", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_chongdanqifa", 1689, 2, "充氮气阀", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_xiedanqifa", 1691, 2, "泄氮气阀", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_jiarexitongfa", 1693, 2, "加热系统阀", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_paifangfa", 1695, 2, "排放阀", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_boliaoji", 1697, 2, "拨料机", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_PHdiaojiebeng", 1699, 2, "PH调节泵", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_diancifa1", 1701, 2, "电磁阀1", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_diancifa2", 1703, 2, "电磁阀2", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_bushuibeng1", 1705, 2, "补水泵1", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_bushuibeng2", 1707, 2, "补水泵2", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_jianwenshuifa", 1709, 2, "减温水阀", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_V1fa", 1711, 2, "V1阀", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_1.DeviceField("de_V2fa", 1713, 2, "V2阀", CTL_NJZJ_1.Map_CTL_NJZJ.coms_device));
        _this.addPoint(new meta_2.ExceptionField("ex_PHzhichuanganqiguzhang", 1752, 2, "PH值传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_jiezhi1wenduchuanganqiguzhang", 1754, 2, "介质1温度传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_jiezhi2wenduchuanganqiguzhang", 1756, 2, "介质2温度传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_jiezhi3wenduchuanganqiguzhang", 1758, 2, "介质3温度传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_jiezhi4wenduchuanganqiguzhang", 1760, 2, "介质4温度传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_jiezhi5wenduchuanganqiguzhang", 1762, 2, "介质5温度传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_jiezhi6wenduchuanganqiguzhang", 1764, 2, "介质6温度传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_danfengyalichuanganqiguzhang", 1766, 2, "氮封压力传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_rongyancaowenduchuanganqiguzhang", 1768, 2, "熔盐槽温度传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_cainuanhuishuiwenduchuanganqiguzhang", 1770, 2, "采暖回水温度传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_shenghuohuishuiwenduchuanganqiguzhang", 1772, 2, "生活回水温度传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_chukouPHzhichuanganqiguzhang", 1774, 2, "出口PH值传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_jinkouPHzhichuanganqiguzhang", 1776, 2, "进口PH值传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_paiyanwendu1chuanganqiguzhang", 1778, 2, "排烟温度1传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_paiyanwendu2chuanganqiguzhang", 1780, 2, "排烟温度2传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_chukouyouyachuanganqiguzhang", 1782, 2, "出口油压传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_jinkouyouyachuanganqiguzhang", 1784, 2, "进口油压传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_huishuiwenduchuanganqiguzhang", 1786, 2, "回水温度传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_chukoudiandaoluchuanganqiguzhang", 1788, 2, "出口电导率传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_jinkoudiandaoluchuanganqiguzhang", 1790, 2, "进口电导率传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_yuanshuixiangyeweichuanganqiguzhang", 1792, 2, "原水箱液位传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_chunshuixiangyeweichuanganqiguzhang", 1794, 2, "纯水箱液位传感器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_jianwenshuifaweifankuixinhaoguzhang", 1796, 2, "减温水阀位反馈信号故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_lushuiyalibiansongqiguzhang", 1798, 2, "炉水压力变送器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_2#morukuozhanmokuaitongxunyichang", 1853, 2, "2#模入扩展模块通讯异常"));
        _this.addPoint(new meta_2.ExceptionField("ex_3#morukuozhanmokuaitongxunyichang", 1855, 2, "3#模入扩展模块通讯异常"));
        _this.addPoint(new meta_2.ExceptionField("ex_4#morukuozhanmokuaitongxunyichang", 1857, 2, "4#模入扩展模块通讯异常"));
        _this.addPoint(new meta_2.ExceptionField("ex_reshuixunhuanbengbianpinqiguzhang", 1859, 2, "热水循环泵变频器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_yuanshuixiangyeweidibaojing", 1861, 2, "原水箱液位低报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_yuanshuibengchukouyaligaobaojing", 1863, 2, "原水泵出口压力高报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_gaoyabengchukouyaligaobaojing", 1865, 2, "高压泵出口压力高报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_dianhuoshibaibaojing", 1867, 2, "点火失败报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_yuanshuibengbianpinqiguzhang", 1869, 2, "原水泵变频器故障"));
        _this.addPoint(new meta_2.ExceptionField("ex_xunhuanbengguozaibaojing", 1871, 2, "循环泵过载报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_ecixunhuanbengguozaibaojing", 1873, 2, "二次循环泵过载报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_jinshuiwendugaobaojing", 1875, 2, "进水温度高报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_gufengjiguozaibaojing", 1877, 2, "鼓风机过载报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_qibao1jixiandishuiweibaojing", 1879, 2, "汽包1极限低水位报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_qibao1dishuiweibaojing", 1881, 2, "汽包1低水位报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_qibao1gaoshuiweibaojing", 1883, 2, "汽包1高水位报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_qibao1shuiweixinhaoluojicuobaojing", 1885, 2, "汽包1水位信号逻辑错报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_qibao2jixiandishuiweibaojing", 1887, 2, "汽包2极限低水位报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_qibao2dishuiweibaojing", 1889, 2, "汽包2低水位报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_qibao2gaoshuiweibaojing", 1891, 2, "汽包2高水位报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_qibao2shuiweixinhaoluojicuobaojing", 1893, 2, "汽包2水位信号逻辑错报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_rongyancaowendugaobaojing", 1895, 2, "熔盐槽温度高报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_rongyancaoyeweidibaojing", 1897, 2, "熔盐槽液位低报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_lutangwendugaobaojing", 1899, 2, "炉膛温度高报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_lutangyaligaobaojing", 1901, 2, "炉膛压力高报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_chuzhajiguzhangbaojing", 1903, 2, "出渣机故障报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_bushuibeng(zhu)guozaibaojing", 1905, 2, "补水泵(主)过载报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_bushuibeng(bei)guozaibaojing", 1907, 2, "补水泵(备)过载报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_xunhuanbeng(zhu)guozaibaojing", 1909, 2, "循环泵(主)过载报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_xunhuanbeng(bei)guozaibaojing", 1911, 2, "循环泵(备)过载报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_waijiechaowenbaojing", 1913, 2, "外接超温报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_panguanwenduchuanganqiguzhangbaojing", 1915, 2, "盘管温度传感器故障报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_panguanwendugaobaojing", 1917, 2, "盘管温度高报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_youyagaobaojing", 1919, 2, "油压高报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_lengningqichukoushuiwengaobaojing", 1921, 2, "冷凝器出口水温高报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_qingzhixingshoudongpaiwucaozuo", 1923, 2, "请执行手动排污操作"));
        _this.addPoint(new meta_2.ExceptionField("ex_chuguanwendugaobaojing", 1925, 2, "储罐温度高报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_chaoyatixing", 1927, 2, "超压提醒"));
        _this.addPoint(new meta_2.ExceptionField("ex_jinkouyouyagaobaojing", 1929, 2, "进口油压高报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_jinkouyouyadibaojing", 1931, 2, "进口油压低报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_refengwendugaobaojing", 1933, 2, "热风温度高报警"));
        _this.addPoint(new meta_2.ExceptionField("ex_kuaisupaifangfaguzhang", 1935, 2, "快速排放阀故障"));
        _this.addPoint(new meta_1.MockField("mo_rongyancaowendu", 2070, 2, "熔盐槽温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_cainuanhuishuiwendu", 2072, 2, "采暖回水温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_shenghuohuishuiwendu", 2074, 2, "生活回水温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_chukouPHzhi", 2076, 2, "出口PH值", "PH", 10));
        _this.addPoint(new meta_1.MockField("mo_jinkouPHzhi", 2078, 2, "进口PH值", "PH", 10));
        _this.addPoint(new meta_1.MockField("mo_paiyanwendu1", 2080, 2, "排烟温度1", "℃"));
        _this.addPoint(new meta_1.MockField("mo_paiyanwendu2", 2082, 2, "排烟温度2", "℃"));
        _this.addPoint(new meta_1.MockField("mo_chukouyouya", 2084, 2, "出口油压", "MPa", 100));
        _this.addPoint(new meta_1.MockField("mo_jinkouyouya", 2086, 2, "进口油压", "MPa", 100));
        _this.addPoint(new meta_1.MockField("mo_huishuiwendu", 2088, 2, "回水温度", "℃"));
        _this.addPoint(new meta_1.MockField("mo_chukoudiandaolu", 2090, 2, "出口电导率", "us/cm", 10));
        _this.addPoint(new meta_1.MockField("mo_jinkoudiandaolu", 2092, 2, "进口电导率", "us/cm", 10));
        _this.addPoint(new meta_1.MockField("mo_yuanshuixiangyewei", 2094, 2, "原水箱液位", "mm"));
        _this.addPoint(new meta_1.MockField("mo_chunshuixiangyewei", 2096, 2, "纯水箱液位", "mm"));
        _this.addPoint(new meta_1.MockField("mo_jianwenshuifaweifankui", 2098, 2, "减温水阀位反馈", "%"));
        _this.addPoint(new meta_1.MockField("mo_lushuiyali", 2100, 2, "炉水压力", "MPa", 100));
        //2173   010305780008c4d9
        _this.addPoint(new meta_1.SettingField("se_yandaodiefaxingcheng", 2155, 2, "烟道蝶阀行程", "℃"));
        _this.addPoint(new meta_1.SettingField("se_yandaodiefayanshi", 2157, 2, "烟道蝶阀延时", "℃"));
        _this.addPoint(new meta_1.SettingField("se_wenchashangxianwendu", 2159, 2, "温差上限温度", "℃"));
        _this.addPoint(new meta_1.SettingField("se_wenchaxiaxianwendu", 2161, 2, "温差下限温度", "℃"));
        _this.addPoint(new meta_1.SettingField("se_chushuitingluwendu", 2163, 2, "出水停炉温度", "℃"));
        _this.addPoint(new meta_1.SettingField("se_zhengqibaojing", 2165, 2, "蒸汽报警", "℃"));
        _this.addPoint(new meta_1.SettingField("se_zhengqitinglu", 2167, 2, "蒸汽停炉", "℃"));
        _this.addPoint(new meta_1.SettingField("se_zhengqimubiaowendu", 2169, 2, "蒸汽目标温度", "℃"));
        return _this;
    }
    return Map_CTL_NJZJ_IP_485_2173;
}(CTL_NJZJ_IP_485_1749_1.Map_CTL_NJZJ_IP_485_1749));
exports.Map_CTL_NJZJ_IP_485_2173 = Map_CTL_NJZJ_IP_485_2173;
