var Chinese = {
  content: "这是中文",
  list_title: "简洁软件",
  list_deletesuccess: "删除成功",
  list_updatesuccess: "修改成功",
  list_refresh: "正在刷新...",
  list_listnull:" 设备列表为空！请在主页添加设备",
  list_runstate: "未连接",
  list_runtime: "运行时间",
  list_rename: "重命名",
  list_delete: "删除",
  list_chooseimg: "选择图片样式",
  list_cancel: "取消",
  list_vertical: "立式",
  list_horizontal: "卧式",
  list_updatename: "修改设备名称",
  list_plename: "请输入设备名称",
  list_yes: "确定",
  list_prompt: "提示",
  list_boldelete: "确定要删除该设备吗？",
  list_error1: "您编号为",
  list_error2: "的设备存在问题，请联系管理员帮您处理",
  detail_pl1: "请输入",
  detail_pl2: "之间的数值",
  detail_zhixing: "执行成功",
  detail_loading: "正在加载...",
  detail_navbar: ['运行信息', '报警信息'],
  detail_cnavbar: ['运行信息', '报警信息', '统计报表', '管理控制'],
  detail_nochuli: "未处理",
  detail_treated: "已处理",
  detail_navbar1: ['运行信息', '报警信息', '统计报表'],
  detail_y:"实时参数 (℃)",
  detail_base: "基本信息",
  detail_mock: "模拟量",
  detail_ex: "当前报警",
  detail_deviceinfo: "设备信息",
  detail_deviceparameters: "设备参数",
  detail_time: "时间",
  detail_chulistates: "处理状态",
  detail_plziduan: "请选择要查看的字段",
  detail_nowzhixing: "立即执行",
  detail_nowzhixing: "参数设置",
  detail_cancel: "取消",
  detail_yes: "确定",
  index_exType: "报警方式",
  index_sold:"设备管理",
  warningType_title: "报警方式",
  warningType_exType: "报警方式",
  warningType_nowChoose: "当前选择：",
  warningType_updatesuccess: "修改成功",
  lanuage_title: "选择语言",
  lanuage_lanuageType: "选择语言",
  lanuage_nowChoose: "当前选择：",
  lanuage_updatesuccess: "修改成功",
  operation_title: "添加设备",
  operation_deviceNo:"设备编号",
  operation_add: "添加",
  operation_scanadd: "扫一扫添加",
  operation_deviceexist: "该设备已存在",
  operation_connfail: "当前网络信号异常，请重新添加",
  operation_addsuccess: "添加成功",
  operation_pleasedeviceno: "请输入设备编号",
  operation_devicenoexist: "该设备不存在",
  operation_devicesucces: "添加成功",
  login_title: "用户登录",
  login_userName: "用户名",
  login_password: "密码",
  login_pleaseuserName: "请输入手机号",
  login_pleasepassword: "请输入密码",
  login_creatuser: "创建一个账户",
  login_forgetPW: "忘记密码",
  login_bindUser: "绑定已有账户",
  login_sccess: "登陆成功",
  login_nouser: "用户名密码不能为空",
  register_title: "注册用户",
  register_pleasephone: "请输入手机号",
  register_getcode: "获取验证码", 
  register_resend: "重新发送",
  register_pleasecode: "请输入验证码", 
  register_pleasename: "请输入真实姓名", 
  register_pleaseename: "请输入企业名称", 
  register_pleasepw: "请输入密码", 
  register_pleasepwagain: "请重新输入密码", 
  register_submit: "提交", 
  register_pleasephone: "号码不能为空", 
  register_falsephone: "手机号格式不正确", 
  register_sendmsg: "短信验证码已发送",
  register_nouser: "未查询到相关用户信息",  
  register_prompt: "提示", 
  register_plphone: "请输入手机号", 
  register_plcode: "请输入验证码", 
  register_plname: "请输入真实姓名", 
  register_falsecode: "验证码错误", 
  register_plpw: "请输入密码", 
  register_twopw: "两次密码不一致", 
  register_existuser: "该用户已存在", 
  register_zhucesuccess: "注册成功", 

 
  forgotPw_title:"忘记密码",
  forgotPw_pleasephone: "请输入手机号",
  forgotPw_getPw: "获取密码",
  forgotPw_nonull: "号码不能为空",
  forgotPw_falsephone: "手机号格式不正确",
  forgotPw_nouser: "该用户不存在",
  forgotPw_newpw: "新密码已发送",
}

module.exports = {
  Content: Chinese
}