var English = {
  content: "这是英文",
  list_title: "Concise software",
  list_deletesuccess: "Delete the success",
  list_updatesuccess: "Modify the success",
  list_refresh: "display refreshing...",
  list_listnull: " The device list is empty! Please add device on home page",
  list_runstate: "Not connected",
  list_runtime: "Run time",
  list_rename: "Rename",
  list_delete: "Delete",
  list_chooseimg: "Select image style",
  list_cancel: "Cancel",
  list_vertical: "Vertical",
  list_horizontal: "Horizontal",
  list_updatename: "Modify device name",
  list_plename: "Please enter the device name",
  list_yes: "Yes",
  list_prompt: "Prompt",
  list_boldelete: "Are you sure you want to delete the device?",
  list_error1: "There is a problem with your equipment numbered ",
  list_error2: ". Please contact the administrator to help you deal with it",
  list_welcome: "Welcome to use",
  list_welcome1: "Concise Boiler Monitoring Applet",
  list_shouquan: "WeChat authorization",
  detail_startstopcontrol: "Start-stop Control",
  detail_yunxing: "Run",
  detail_daiming: "On Standby",
  detail_pl1: "Please enter a value between",
  detail_pl2: "",
  detail_zhixing: "Execute successfully",
  detail_loading: "loading...",
  detail_navbar: ['Run information', 'Alarm information'],
  detail_cnavbar: ['Run information', 'Alarm information', 'Statistical reports', 'Management control'],
  detail_nochuli: "untreated",
  detail_treated: "treated",
  detail_navbar1: ['Run information', 'Alarm information', 'Statistical reports'],
  detail_y: "Real-time parameter (℃)",
  detail_base: "Basic information",
  detail_mock: "Mock value",
  detail_ex: "Current alarm",
  detail_deviceinfo: "Device information",
  detail_deviceparameters: "Device parameters",
  detail_time: "Time",
  detail_chulistates: "Processing state",
  detail_plziduan: "Select the field you want to view",
  detail_nowzhixing: "Executed immediately",
  detail_nowzhixing: "Parameter Settings",
  detail_cancel: "Cancel",
  detail_yes: "Yes",
  index_exType: "Alarm way",
  index_sold:"Equipment management",
  index_canIUse: "Binding platform account",
  warningType_title: "Alarm way",
  warningType_exType: "Alarm way",
  warningType_nowChoose: "Current selection",
  warningType_updatesuccess: "Modify the success",
  lanuage_title: "Select the language",
  lanuage_lanuageType: "Select the language",
  lanuage_nowChoose: "Current selection",
  lanuage_updatesuccess: "Modify the success",
  operation_title: "Add Device",
  operation_deviceNo: "Device Number",
  operation_add: "Add",
  operation_scanadd: " Scan add",
  operation_deviceexist: "The device already exists",
  operation_addsuccess: "Add  success",
  operation_pleasedeviceno: "Please enter the device number",
  operation_devicenoexist: "The device does not exist",
  operation_connfail: "The current network signal is abnormal, please add again",
  operation_devicesucces: "Add  success",
  login_title: "User Login",
  login_userName: "Username",
  login_password: "Password",
  login_pleaseuserName: "Please enter mobile phone ",
  login_pleasepassword: "Please enter  password",
  login_creatuser: "Create an account",
  login_forgetPW: "Forgot password",
  login_bindUser: "Binding account",
  login_nouser: "The username and password cannot be empty",
  login_sccess: "Log in successfully",
  register_title: "Registered users",
  register_pleasephone: "Please enter mobile phone ",
  register_getcode: "Authcode",
  register_resend: "Resend", 
  register_pleasecode: "Please enter the verification code",
  register_pleasename: "Please enter your real name",
  register_pleaseename: "Please enter a business name",
  register_pleasepw: "Please enter your password",
  register_pleasepwagain: "Please re-enter your password",
  register_submit: "submit", 
  register_pleasephone: "The number cannot be empty", 
  register_falsephone: "The phone number format is not correct", 
  register_sendmsg: "SMS verification code has been sent", 
  register_prompt: "prompt", 
  register_plphone: "Please enter your mobile phone number", 
  register_plcode: "Please enter the verification code", 
  register_plname: "Please enter your real name", 
  register_falsecode: "Verification code error", 
  register_plpw: "Please enter your password", 
  register_twopw: "The passwords do not match", 
  register_existuser: "The user already exists", 
  register_zhucesuccess: "Registered successfully", 
  register_pguojia: "Please enter the country", 
  forgotPw_title: "Forgot password",
  forgotPw_pleasephone: "Please enter your mobile phone number",
  forgotPw_getPw: "To get the password",
  forgotPw_nonull: "The number cannot be empty",
  forgotPw_falsephone: "The phone number format is not correct",
  forgotPw_nouser: "The user does not exist",
  forgotPw_newpw: "The new password has been sent",
}

module.exports = {
  Content: English
}